from helpers_html import S, Sx, M, T, quiz

def get_quizzes():
    quizzes = []

    quizzes.append(quiz(
        "Éléments interactifs HTML5 : details et summary",
        "Créer des widgets de divulgation natifs sans JavaScript.",
        [
            S("Quel élément HTML5 crée un widget extensible/réductible natif (accordéon) sans JavaScript ?",
              ["<details>", "<accordion>", "<expand>", "<toggle>"]),
            S("Quel élément enfant de <details> définit le texte toujours visible qui sert de déclencheur ?",
              ["<summary>", "<title>", "<header>", "<legend>"]),
            S("Quel attribut booléen de <details> permet d'afficher le contenu ouvert par défaut au chargement ?",
              ["open", "expanded", "visible", "show"]),
            Sx("Que se passe-t-il par défaut quand on clique sur l'élément <summary> d'un <details> fermé ?",
               ["Le contenu du details s'affiche (il s'ouvre)", "La page se recharge", "Un formulaire est soumis", "Rien, il faut du JavaScript"], 0),
            T("L'élément <details> peut fonctionner correctement même si JavaScript est désactivé dans le navigateur.", True),
            T("Un seul élément <summary> est autorisé comme premier enfant direct d'un <details>.", True),
            M("Quelles affirmations sur <details>/<summary> sont correctes ?",
              ["Ils sont nativement accessibles au clavier", "On peut styliser le triangle indicateur avec CSS"],
              ["Ils nécessitent obligatoirement une bibliothèque JavaScript", "Ils ne peuvent contenir que du texte brut"]),
            M("Quels cas d'usage sont pertinents pour <details> ?",
              ["Une FAQ avec questions/réponses repliables", "Afficher des informations complémentaires optionnelles"],
              ["Remplacer systématiquement tous les formulaires", "Charger une vidéo en arrière-plan"]),
        ],
    ))

    quizzes.append(quiz(
        "L'élément dialog",
        "Afficher des fenêtres modales natives en HTML5.",
        [
            S("Quel élément HTML5 représente une boîte de dialogue ou une fenêtre modale native ?",
              ["<dialog>", "<modal>", "<popup>", "<window>"]),
            S("Quelle méthode JavaScript permet d'ouvrir un <dialog> en mode modal (bloquant le reste de la page) ?",
              ["showModal()", "open()", "show()", "display()"]),
            S("Quel attribut booléen, présent dans le DOM quand le dialogue est ouvert, indique son état ?",
              ["open", "visible", "active", "shown"]),
            Sx("Quelle pseudo-classe CSS permet de styliser l'arrière-plan assombri derrière un <dialog> ouvert en mode modal ?",
               ["::backdrop", "::overlay", "::modal-bg", "::dim"], 0),
            T("La méthode show() ouvre le dialogue en mode non modal, en laissant le reste de la page interactif.", True),
            T("Un élément <dialog> sans aucun attribut open est visible par défaut dans la page.", False),
            M("Quelles méthodes JavaScript sont associées à l'élément <dialog> ?",
              ["showModal()", "close()", "show()"],
              ["openWindow()", "alert()"]),
            M("Quelles affirmations sur <dialog> sont correctes ?",
              ["Il peut contenir un formulaire avec method='dialog'", "Il améliore l'accessibilité par rapport à une modale recréée en div"],
              ["Il remplace obligatoirement toutes les balises <form>", "Il ne peut jamais être fermé par l'utilisateur"]),
        ],
    ))

    quizzes.append(quiz(
        "Historique : éléments dépréciés vs HTML5",
        "Reconnaître les anciennes balises remplacées par des approches modernes.",
        [
            S("Quel ancien élément servait à mettre en évidence du texte en gras, aujourd'hui remplacé sémantiquement par <strong> pour l'importance ?",
              ["<b> reste valide mais sans signification sémantique forte", "<bold>", "<emphase>", "<heavy>"]),
            S("Quel ancien élément, aujourd'hui obsolète, servait à faire défiler du texte automatiquement ?",
              ["<marquee>", "<scroll>", "<move>", "<slide>"]),
            S("Quel ancien attribut de présentation, utilisé sur <body>, définissait la couleur de fond et est aujourd'hui remplacé par CSS ?",
              ["bgcolor", "background-color", "bg", "color-bg"]),
            Sx("Quel élément structurait les anciennes pages en plusieurs zones de défilement indépendantes avant HTML5, aujourd'hui déconseillé ?",
               ["<frameset>", "<iframe>", "<section>", "<div>"], 0),
            T("L'élément <center> permettait autrefois de centrer du contenu, mais cette approche est aujourd'hui remplacée par CSS.", True),
            T("L'élément <font> permettait de définir la police et la taille du texte directement en HTML, une pratique aujourd'hui obsolète en faveur du CSS.", True),
            M("Quels éléments ou attributs sont considérés comme obsolètes ou dépréciés en HTML5 ?",
              ["<center>", "<font>", "<marquee>"],
              ["<section>", "<article>"]),
            M("Quelles raisons justifient l'abandon des balises de présentation comme <font> ou bgcolor ?",
              ["Séparer le contenu (HTML) de la présentation (CSS)", "Faciliter la maintenance et la cohérence du style"],
              ["Elles ralentissaient JavaScript", "Elles étaient interdites par le W3C dès 1995"]),
        ],
    ))

    quizzes.append(quiz(
        "Script, defer et async : placement et chargement",
        "Comprendre comment et où charger les scripts JavaScript dans une page.",
        [
            S("Quel élément permet d'inclure ou de référencer du code JavaScript dans une page HTML ?",
              ["<script>", "<js>", "<code>", "<javascript>"]),
            S("Quel attribut de <script> permet de télécharger le script en parallèle puis de l'exécuter après l'analyse complète du HTML, en respectant l'ordre des scripts ?",
              ["defer", "async", "delay", "lazy"]),
            S("Quel attribut de <script> permet de télécharger le script en parallèle et de l'exécuter dès qu'il est prêt, sans respecter l'ordre ?",
              ["async", "defer", "parallel", "instant"]),
            Sx("Pourquoi place-t-on traditionnellement les balises <script> juste avant la fermeture de </body> ?",
               ["Pour ne pas bloquer le rendu du contenu HTML pendant le téléchargement du script", "Pour que le script s'exécute avant le CSS", "Parce que c'est obligatoire en HTML5", "Pour réduire la taille du fichier HTML"], 0),
            T("Un script sans attribut async ni defer, placé dans le head, bloque le parsing du HTML jusqu'à son téléchargement et son exécution complets.", True),
            T("Les attributs async et defer n'ont aucun effet sur un script qui ne possède pas d'attribut src.", True),
            M("Quels attributs influencent le comportement de chargement d'un <script> externe ?",
              ["async", "defer", "src"],
              ["preload-now", "blocking-off"]),
            M("Quelles affirmations sur defer sont correctes ?",
              ["Les scripts en defer s'exécutent dans l'ordre où ils apparaissent dans le document", "Ils s'exécutent après la fin du parsing du HTML"],
              ["Ils s'exécutent avant le téléchargement du document HTML", "Ils empêchent totalement l'utilisation d'event listeners"]),
        ],
    ))

    quizzes.append(quiz(
        "Canvas : notions de base",
        "Découvrir l'élément canvas pour le dessin via JavaScript.",
        [
            S("Quel élément HTML5 fournit une zone de dessin programmable via JavaScript ?",
              ["<canvas>", "<draw>", "<svg>", "<paint>"]),
            S("Quelle méthode JavaScript permet d'obtenir le contexte de dessin 2D d'un canvas ?",
              ["getContext('2d')", "getDrawing()", "getCanvas2D()", "draw2D()"]),
            S("Quels attributs définissent la résolution interne (en pixels) d'un élément canvas ?",
              ["width et height", "size et scale", "resolution", "dimension"]),
            Sx("Que contient un élément <canvas> par défaut, sans aucun script associé ?",
               ["Une zone vide, transparente ou blanche selon le style", "Une grille de coordonnées visible", "Un message d'erreur", "Une image de remplacement automatique"], 0),
            T("Le contenu dessiné sur un canvas n'est pas un ensemble d'éléments du DOM individuels, mais une image bitmap générée par script.", True),
            T("Le contenu textuel placé entre les balises <canvas> et </canvas> s'affiche par-dessus le dessin une fois le script exécuté.", False),
            M("Quels contextes de rendu peut-on obtenir depuis un élément canvas ?",
              ["2d", "webgl"],
              ["svg-context", "html-context"]),
            M("Quelles affirmations sur l'élément canvas sont correctes ?",
              ["Il est souvent utilisé pour des graphiques, jeux ou visualisations dynamiques", "Son contenu doit être redessiné par script si la fenêtre est redimensionnée"],
              ["Il génère automatiquement des éléments accessibles pour chaque forme dessinée", "Il remplace obligatoirement toutes les images statiques d'un site"]),
        ],
    ))

    quizzes.append(quiz(
        "SVG : notions de base intégrées en HTML",
        "Intégrer des graphiques vectoriels directement dans une page HTML.",
        [
            S("Que signifie l'acronyme SVG ?",
              ["Scalable Vector Graphics", "Simple Visual Graphics", "Standard Vector Graphic", "Structured Vector Generator"]),
            S("Quel élément SVG permet de dessiner un cercle ?",
              ["<circle>", "<round>", "<oval>", "<ball>"]),
            S("Quel attribut SVG définit l'espace de coordonnées visible d'un dessin vectoriel ?",
              ["viewBox", "viewport", "canvas-area", "frame"]),
            Sx("Quel avantage principal le format SVG offre-t-il par rapport à une image bitmap (comme un PNG) ?",
               ["Il reste net à n'importe quelle taille car il est vectoriel", "Il se charge toujours plus vite qu'un PNG", "Il ne peut pas être animé", "Il ne supporte pas les couleurs"], 0),
            T("Le SVG peut être intégré directement dans le code HTML comme un élément inline, sans fichier externe.", True),
            T("Les éléments SVG ne peuvent en aucun cas être stylisés avec CSS.", False),
            M("Quels éléments SVG de base servent à dessiner des formes ?",
              ["<circle>", "<rect>", "<path>"],
              ["<shape>", "<form-svg>"]),
            M("Quelles affirmations sur le SVG sont correctes ?",
              ["C'est un format basé sur XML", "Il peut être manipulé via JavaScript et le DOM"],
              ["Il est uniquement utilisable comme fichier image externe", "Il remplace systématiquement le canvas pour tout usage"]),
        ],
    ))

    quizzes.append(quiz(
        "Web components et templates : notions de base",
        "Découvrir les briques de réutilisabilité native du HTML moderne.",
        [
            S("Quel élément HTML5 permet de définir un fragment de markup réutilisable, inerte tant qu'il n'est pas activé par script ?",
              ["<template>", "<fragment>", "<component>", "<reuse>"]),
            S("Quel terme désigne un ensemble de technologies natives du navigateur permettant de créer des éléments HTML personnalisés et réutilisables ?",
              ["Web Components", "Web Modules", "Web Fragments", "Web Includes"]),
            S("Quel élément permet de créer un encapsulement de style et de structure isolé via le DOM, appelé 'shadow DOM' ?",
              ["attachShadow() crée une racine de Shadow DOM", "<shadow>", "<isolated>", "<scoped>"]),
            Sx("Quelle caractéristique principale du contenu d'un <template> le distingue d'un <div> classique ?",
               ["Son contenu n'est pas rendu ni exécuté tant qu'il n'est pas cloné et inséré via JavaScript", "Il s'affiche immédiatement en gras", "Il ne peut contenir aucune balise HTML", "Il se charge depuis un fichier externe obligatoirement"], 0),
            T("Les scripts contenus à l'intérieur d'un <template> ne s'exécutent pas tant que le contenu n'a pas été inséré activement dans le DOM.", True),
            T("Les éléments personnalisés (custom elements) doivent obligatoirement contenir un tiret dans leur nom de balise, par exemple mon-element.", True),
            M("Quelles technologies font partie de l'écosystème des Web Components ?",
              ["Custom Elements", "Shadow DOM", "HTML Templates"],
              ["JSON Schema", "WebAssembly"]),
            M("Quelles affirmations sur <template> sont correctes ?",
              ["Son contenu est accessible via la propriété content en JavaScript", "Il permet de préparer un fragment HTML répétable sans le dupliquer dans le DOM visible"],
              ["Il est obligatoirement affiché sur la page dès le chargement", "Il remplace les feuilles de style CSS"]),
        ],
    ))

    quizzes.append(quiz(
        "Formulaires avancés : datalist",
        "Proposer des suggestions de saisie avec datalist.",
        [
            S("Quel élément permet d'associer une liste de suggestions prédéfinies à un champ texte ?",
              ["<datalist>", "<suggestions>", "<autocomplete>", "<options>"]),
            S("Quel attribut d'un <input> permet de le relier à un <datalist> via son identifiant ?",
              ["list", "data", "ref", "source"]),
            S("Quel élément définit chaque suggestion individuelle à l'intérieur d'un <datalist> ?",
              ["<option>", "<item>", "<suggestion>", "<li>"]),
            Sx("Quelle différence majeure existe entre <datalist> et <select> du point de vue de l'utilisateur ?",
               ["Avec datalist, l'utilisateur peut saisir une valeur libre en plus des suggestions", "Avec select, on peut saisir n'importe quel texte librement", "datalist n'accepte aucune saisie clavier", "select ne propose jamais de liste déroulante"], 0),
            T("Le <datalist> est généralement rendu invisible directement et n'apparaît que sous forme de suggestions lors de la saisie dans le champ associé.", True),
            T("Un <input> ne peut être associé qu'à un seul <datalist> via l'attribut list à la fois.", True),
            M("Quelles affirmations sur <datalist> sont correctes ?",
              ["Il améliore l'expérience de saisie sans imposer une liste fermée", "Ses options sont définies avec des éléments <option>"],
              ["Il empêche toute saisie libre dans le champ", "Il remplace obligatoirement les boutons radio"]),
            M("Quels éléments de formulaire permettent de proposer des choix à l'utilisateur ?",
              ["<datalist>", "<select>"],
              ["<fieldset>", "<label>"]),
        ],
    ))

    quizzes.append(quiz(
        "Formulaires avancés : select, option et optgroup",
        "Structurer des listes déroulantes complexes avec des groupes d'options.",
        [
            S("Quel élément crée une liste déroulante de choix dans un formulaire ?",
              ["<select>", "<dropdown>", "<list>", "<choice>"]),
            S("Quel élément représente un choix individuel à l'intérieur d'un <select> ?",
              ["<option>", "<item>", "<choice>", "<entry>"]),
            S("Quel élément permet de regrouper visuellement plusieurs <option> sous un même libellé dans un <select> ?",
              ["<optgroup>", "<group>", "<section>", "<category>"]),
            Sx("Quel attribut booléen sur <select> permet à l'utilisateur de choisir plusieurs options simultanément ?",
               ["multiple", "many", "checkbox", "multi-select"], 0),
            T("L'attribut selected sur un <option> permet de le présélectionner par défaut.", True),
            T("L'élément <optgroup> peut lui-même contenir un autre <optgroup> imbriqué indéfiniment.", False),
            M("Quels attributs sont valides sur l'élément <option> ?",
              ["value", "selected", "disabled"],
              ["checked", "href"]),
            M("Quelles affirmations sur <optgroup> sont correctes ?",
              ["Il possède un attribut label pour son titre", "Il sert uniquement à regrouper des <option>, pas du texte libre"],
              ["Il remplace l'attribut multiple", "Il doit obligatoirement contenir exactement deux options"]),
        ],
    ))

    quizzes.append(quiz(
        "Structure sémantique avancée : figure et figcaption",
        "Associer une légende à une image, un schéma ou un extrait de code.",
        [
            S("Quel élément regroupe un contenu illustratif (image, schéma, code) et sa légende ?",
              ["<figure>", "<image-group>", "<caption-box>", "<illustration>"]),
            S("Quel élément fournit la légende associée au contenu d'un <figure> ?",
              ["<figcaption>", "<caption>", "<legend>", "<desc>"]),
            S("Où l'élément <figcaption> peut-il être positionné à l'intérieur de <figure> ?",
              ["En premier ou en dernier enfant de figure", "Uniquement au milieu", "Uniquement avant le contenu", "Il doit être en dehors de figure"]),
            Sx("Quel est l'avantage sémantique d'utiliser <figure> plutôt qu'un simple <div> autour d'une image avec sa légende ?",
               ["Cela indique explicitement la relation entre le contenu et sa légende pour les technologies d'assistance", "Cela rend l'image plus grande automatiquement", "Cela améliore la vitesse de chargement", "Cela évite d'utiliser l'attribut alt"], 0),
            T("Un <figure> peut contenir plusieurs images partageant une seule légende commune.", True),
            T("L'élément <figcaption> est obligatoire dès qu'on utilise un <figure>.", False),
            M("Quels types de contenus peuvent être englobés par <figure> ?",
              ["Une image illustrative", "Un extrait de code", "Un graphique ou diagramme"],
              ["Le menu de navigation principal", "Le pied de page du site"]),
            M("Quelles affirmations sur <figure>/<figcaption> sont correctes ?",
              ["Ils renforcent la sémantique du contenu illustratif", "Le contenu de figure reste pertinent même déplacé du flux principal"],
              ["Ils remplacent obligatoirement l'attribut alt de l'image", "Ils ne peuvent contenir aucun élément interactif"]),
        ],
    ))

    quizzes.append(quiz(
        "Structure sémantique avancée : time, mark, progress, meter",
        "Donner du sens à des dates, surlignages et indicateurs de progression.",
        [
            S("Quel élément représente une date ou une heure dans un format compréhensible par les machines, via l'attribut datetime ?",
              ["<time>", "<date>", "<clock>", "<calendar>"]),
            S("Quel élément met en évidence un passage de texte pertinent, comme un surlignage ?",
              ["<mark>", "<highlight>", "<em>", "<strong>"]),
            S("Quel élément représente l'avancement d'une tâche, comme une barre de progression ?",
              ["<progress>", "<meter>", "<status>", "<loading>"]),
            Sx("Quel élément représente une mesure scalaire dans une plage connue, par exemple un niveau de batterie ou un score, sans forcément représenter une tâche en cours ?",
               ["<meter>", "<progress>", "<gauge>", "<range>"], 0),
            T("L'attribut datetime de <time> permet de fournir une valeur de date/heure normalisée même si le texte affiché est rédigé en langage naturel.", True),
            T("Les éléments <progress> et <meter> sont strictement identiques et interchangeables dans tous les cas.", False),
            M("Quels attributs sont associés à l'élément <meter> ?",
              ["min", "max", "value"],
              ["loop", "autoplay"]),
            M("Quelles affirmations sur <mark> sont correctes ?",
              ["Il est souvent utilisé pour surligner un résultat de recherche dans un texte", "Son rendu par défaut est généralement un fond jaune"],
              ["Il remplace la balise <strong> pour l'importance sémantique forte", "Il ne peut être utilisé qu'une fois par page"]),
        ],
    ))

    quizzes.append(quiz(
        "Encodage de caractères en HTML",
        "Comprendre l'importance de l'encodage pour un affichage correct du texte.",
        [
            S("Quel jeu de caractères est aujourd'hui la norme recommandée pour quasiment tous les sites web ?",
              ["UTF-8", "Latin-1", "ASCII", "Windows-1252"]),
            S("Où doit être déclaré l'encodage de caractères d'une page HTML pour être pris en compte correctement et rapidement ?",
              ["Dans une balise meta charset au tout début de head", "Dans le pied de page", "Dans le nom du fichier", "Dans l'attribut lang de html"]),
            S("Quel problème visuel typique survient lorsqu'un document est mal encodé (mojibake) ?",
              ["Des caractères accentués ou spéciaux s'affichent de façon incorrecte ou déformée", "La page ne charge plus aucune image", "Le CSS est ignoré", "Le JavaScript ne s'exécute plus"]),
            Sx("Quel est l'intérêt principal de l'encodage UTF-8 par rapport à des encodages plus anciens comme ISO-8859-1 ?",
               ["Il peut représenter quasiment tous les caractères et symboles du monde, y compris les emojis", "Il est plus rapide à charger systématiquement", "Il supprime le besoin d'entités HTML", "Il est uniquement compatible avec l'anglais"], 0),
            T("Une déclaration d'encodage incorrecte ou absente peut entraîner un affichage erroné des caractères accentués comme é, à ou ç.", True),
            T("L'attribut lang sur l'élément <html> définit l'encodage de caractères de la page.", False),
            M("Quelles bonnes pratiques concernent l'encodage de caractères d'une page HTML ?",
              ["Déclarer UTF-8 via meta charset en début de head", "Enregistrer effectivement le fichier source en UTF-8"],
              ["Ne jamais déclarer d'encodage et laisser le navigateur deviner", "Utiliser un encodage différent par page d'un même site sans cohérence"]),
            M("Quelles affirmations sur l'attribut lang de <html> sont correctes ?",
              ["Il aide les lecteurs d'écran à choisir la bonne prononciation", "Il peut améliorer le référencement multilingue"],
              ["Il définit l'encodage des caractères", "Il remplace la balise meta charset"]),
        ],
    ))

    return quizzes
