from helpers_html import S, Sx, M, T, quiz

def get_quizzes():
    quizzes = []

    quizzes.append(quiz(
        "Les attributs name et id : usages distincts",
        "Différencier l'attribut name, surtout utilisé en formulaire, de l'attribut id.",
        [
            S("Quel attribut est principalement utilisé pour identifier la donnée d'un champ de formulaire lors de la soumission ?",
              ["name", "id", "value", "key"]),
            S("Plusieurs champs de formulaire peuvent-ils partager le même attribut name ?",
              ["Oui, par exemple pour un groupe de boutons radio", "Non, jamais, comme id", "Seulement pour les champs cachés", "Seulement pour les select"]),
            S("Quel attribut sert de cible pour les sélecteurs CSS #identifiant ou les ancres #fragment ?",
              ["id", "name", "class", "ref"]),
            Sx("Pourquoi un champ de formulaire sans attribut name ne sera-t-il généralement pas inclus dans les données envoyées au serveur ?",
               ["Parce que name est la clé utilisée pour construire les paires clé/valeur soumises", "Parce que id est obligatoire pour la soumission", "Parce que tous les champs sont envoyés sauf exception explicite", "Parce que value seul suffit toujours sans name"], 0),
            T("Un champ peut avoir à la fois un id (pour le CSS/JS/label) et un name (pour la soumission), avec des valeurs différentes.", True),
            T("L'attribut name doit obligatoirement être unique pour chaque champ d'un même formulaire.", False),
            M("Quelles affirmations sur name et id sont correctes ?",
              ["name est central pour la construction des données de formulaire", "id doit être unique dans tout le document"],
              ["Les deux attributs sont strictement interchangeables dans tous les contextes", "name ne peut jamais être répété, même pour des radios"]),
            M("Quels éléments utilisent typiquement l'attribut name pour la soumission de formulaire ?",
              ["<input>", "<select>", "<textarea>"],
              ["<img>", "<a>"]),
        ],
    ))

    quizzes.append(quiz(
        "Le bouton et l'icône accessible (texte caché visuellement)",
        "Rendre accessibles des boutons qui n'affichent qu'une icône.",
        [
            S("Comment rendre accessible un bouton qui n'affiche visuellement qu'une icône sans texte visible ?",
              ["En ajoutant un attribut aria-label décrivant l'action, ou un texte masqué visuellement mais lisible par un lecteur d'écran", "En ajoutant uniquement une couleur de fond différente", "En augmentant la taille de l'icône", "Aucune action n'est nécessaire, les icônes sont toujours comprises"]),
            S("Quel attribut ARIA est souvent utilisé pour fournir un nom accessible direct à un bouton icône, sans modifier le contenu visible ?",
              ["aria-label", "alt (qui ne s'applique pas à button)", "title obligatoirement", "data-label"]),
            S("Pourquoi se reposer uniquement sur l'attribut title pour décrire un bouton icône est-il insuffisant pour l'accessibilité ?",
              ["Parce que son support par les lecteurs d'écran et son affichage sont incohérents selon les navigateurs et appareils", "Parce que title est interdit en HTML5", "Parce que title change la couleur du bouton", "Parce que title empêche le clic"]),
            Sx("Quelle technique consiste à inclure du texte dans le bouton mais masqué visuellement via CSS (mais lisible par les technologies d'assistance) ?",
               ["Une classe utilitaire de type 'sr-only' (visually hidden)", "display:none pur et simple", "aria-hidden='true' sur le texte", "visibility:hidden classique"], 0),
            T("Un bouton icône sans nom accessible (ni texte, ni aria-label) est généralement annoncé de façon peu utile ou ambiguë par un lecteur d'écran.", True),
            T("aria-hidden='true' appliqué au texte alternatif d'un bouton icône le rendrait accessible aux lecteurs d'écran.", False),
            M("Quelles techniques permettent de rendre un bouton icône accessible ?",
              ["aria-label sur le bouton", "Texte visuellement masqué mais présent dans le DOM"],
              ["aria-hidden sur le bouton lui-même sans alternative", "Aucune action, les icônes suffisent toujours"]),
            M("Quelles affirmations sur l'accessibilité des boutons icônes sont correctes ?",
              ["Un nom accessible explicite est nécessaire si le texte visible est absent", "display:none cache le texte aussi bien visuellement qu'aux lecteurs d'écran"],
              ["Les icônes sont universellement comprises sans description", "title est la méthode la plus fiable et universelle"]),
        ],
    ))

    quizzes.append(quiz(
        "Frame et iframe : différences historiques",
        "Comprendre pourquoi frameset a été abandonné au profit d'iframe.",
        [
            S("Quel ancien élément permettait de diviser une fenêtre de navigateur en plusieurs zones de défilement indépendantes, chacune chargeant un document HTML distinct ?",
              ["<frameset> avec des <frame>", "<iframe>", "<section>", "<div split>"]),
            S("Quel élément moderne permet d'intégrer un document distinct à l'intérieur du flux normal d'une page, sans diviser toute la fenêtre ?",
              ["<iframe>", "<frameset>", "<frame>", "<embed-page>"]),
            S("Pourquoi frameset a-t-il été retiré du HTML5 standard (hors variante de transition) ?",
              ["Il posait des problèmes d'accessibilité, de SEO, de navigation (bouton retour) et d'ergonomie générale", "Il était trop rapide à charger", "Il était incompatible avec le CSS", "Il ne permettait pas d'afficher du texte"]),
            Sx("Quel avantage présente <iframe> par rapport à l'ancien <frameset> en termes de flexibilité de mise en page ?",
               ["Il peut être positionné n'importe où dans une page normale comme un élément parmi d'autres", "Il occupe obligatoirement toute la fenêtre", "Il ne peut afficher que des images", "Il remplace obligatoirement le head du document"], 0),
            T("frameset est absent des recommandations HTML5 standard, bien qu'un mode de transition ait existé pour la compatibilité historique.", True),
            T("Un <iframe> divise obligatoirement toute la fenêtre du navigateur en plusieurs cadres comme le faisait frameset.", False),
            M("Quels problèmes étaient associés à l'usage de frameset ?",
              ["Difficulté de mise en favoris d'une vue précise", "Problèmes d'accessibilité pour les lecteurs d'écran", "Mauvaise indexation par les moteurs de recherche"],
              ["Incompatibilité totale avec le HTML", "Impossibilité d'afficher du texte"]),
            M("Quelles affirmations sur iframe sont correctes ?",
              ["Il s'intègre dans le flux normal du document comme un élément remplacé", "Il peut être stylisé et dimensionné avec CSS comme d'autres éléments"],
              ["Il remplace obligatoirement tout le contenu de la page", "Il est interdit en HTML5"]),
        ],
    ))

    quizzes.append(quiz(
        "Les fragments d'URL et le routage côté client (notions de base)",
        "Comprendre comment le fragment d'URL peut être utilisé au-delà des simples ancres.",
        [
            S("Quel caractère introduit un fragment d'URL pointant potentiellement vers un identifiant d'élément dans la page ?",
              ["Le caractère # (dièse)", "Le caractère ? (point d'interrogation)", "Le caractère & (esperluette)", "Le caractère / (slash)"]),
            S("Le fragment d'URL (après le #) est-il envoyé au serveur lors d'une requête HTTP classique de navigation ?",
              ["Non, il reste traité côté client par le navigateur", "Oui, systématiquement transmis au serveur", "Seulement avec la méthode POST", "Seulement si JavaScript est désactivé"]),
            S("Quelle API JavaScript moderne permet de manipuler l'URL (y compris le chemin) sans recharger la page, utilisée par certains frameworks de routage côté client ?",
              ["History API (pushState, replaceState)", "Fragment API", "Route API native obligatoire", "URLRewriter natif"]),
            Sx("Pourquoi certaines applications historiques utilisaient-elles le fragment d'URL (#) pour simuler des routes côté client avant l'arrivée généralisée de la History API ?",
               ["Parce que changer le fragment ne provoque pas de rechargement de page tout en modifiant l'URL visible", "Parce que le fragment est obligatoire pour charger du CSS", "Parce que le fragment active automatiquement le SEO", "Parce que le fragment supprime le besoin de JavaScript"], 0),
            T("Une ancre interne classique (#section) et un usage de routage applicatif via le fragment exploitent tous deux le fait que le navigateur ne recharge pas la page pour un simple changement de fragment.", True),
            T("Le contenu après # dans une URL est toujours obligatoirement un identifiant d'élément HTML existant sur la page.", False),
            M("Quelles affirmations sur le fragment d'URL (#) sont correctes ?",
              ["Il n'est pas transmis au serveur lors d'une requête HTTP standard", "Il peut servir à la fois pour des ancres et pour du routage applicatif"],
              ["Il est obligatoire pour charger n'importe quelle page", "Il remplace les paramètres de requête après le ?"]),
            M("Quelles technologies sont liées à la gestion d'URL côté client sans rechargement complet de page ?",
              ["History API", "Fragment (#) historique pour le routage"],
              ["Balises meta robots", "Attribut colspan"]),
        ],
    ))

    quizzes.append(quiz(
        "Sémantique avancée : la balise data et son usage",
        "Associer une valeur machine-lisible à un contenu lisible par l'humain.",
        [
            S("Quel élément HTML5 associe une valeur machine-lisible à un contenu affiché de façon lisible pour l'humain ?",
              ["<data>", "<value>", "<meta-inline>", "<machine>"]),
            S("Quel attribut de l'élément <data> porte la valeur destinée au traitement programmatique ?",
              ["value", "data-value", "content", "machine-value"]),
            S("Dans quel contexte l'élément <data> serait-il pertinent, par exemple sur une page de produit ?",
              ["Pour afficher une référence produit lisible tout en associant un code interne précis en attribut value", "Pour remplacer toutes les balises meta", "Pour structurer un tableau", "Pour créer un lien hypertexte"]),
            Sx("Quelle est la principale différence entre <data> et <time>, qui semble similaire dans son principe ?",
               ["<time> est spécifiquement dédié aux dates et heures, tandis que <data> est générique pour toute autre valeur machine-lisible", "Ils sont strictement identiques sans nuance", "<data> ne fonctionne que dans les formulaires", "<time> ne peut contenir aucun attribut"], 0),
            T("L'élément <data> n'est pas un champ de formulaire et n'est pas soumis lors de l'envoi d'un formulaire.", True),
            T("L'élément <data> est obligatoire pour qu'un document HTML5 soit considéré comme valide.", False),
            M("Quelles affirmations sur l'élément <data> sont correctes ?",
              ["Il sépare le texte affiché du contenu machine-lisible via l'attribut value", "Il peut être utile pour des microformats ou scripts personnalisés"],
              ["Il remplace l'élément <time> pour les dates", "Il s'agit d'un champ de saisie interactif"]),
            M("Quels éléments HTML5 associent un contenu affiché à une valeur structurée distincte ?",
              ["<data>", "<time>"],
              ["<span>", "<div>"]),
        ],
    ))

    quizzes.append(quiz(
        "Les attributs spellcheck, autocapitalize et inputmode",
        "Adapter le comportement de saisie mobile et la vérification orthographique.",
        [
            S("Quel attribut global active ou désactive la vérification orthographique native du navigateur sur un champ éditable ?",
              ["spellcheck", "autocorrect natif HTML standard", "grammar", "check"]),
            S("Quel attribut influence la capitalisation automatique du texte saisi, particulièrement utile sur mobile ?",
              ["autocapitalize", "uppercase", "capslock", "textcase"]),
            S("Quel attribut suggère au système le type de clavier virtuel le plus adapté à afficher, par exemple numérique pour un code postal ?",
              ["inputmode", "keyboardtype", "virtualkeyboard", "numpad"]),
            Sx("Quelle valeur de inputmode afficherait un clavier optimisé pour la saisie d'un numéro de téléphone sur mobile ?",
               ["tel", "numeric", "decimal", "text"], 0),
            T("inputmode influence l'apparence du clavier virtuel mais ne remplace pas la validation réelle du format avec type ou pattern.", True),
            T("spellcheck modifie la valeur réellement envoyée au serveur lors de la soumission du formulaire.", False),
            M("Quels attributs influencent l'expérience de saisie sur mobile sans changer la validation des données ?",
              ["inputmode", "autocapitalize", "spellcheck"],
              ["required", "pattern"]),
            M("Quelles affirmations sur inputmode sont correctes ?",
              ["Il peut prendre des valeurs comme numeric, email, url", "Il est purement une suggestion d'affichage de clavier, pas une contrainte de validation"],
              ["Il garantit que seuls les chiffres puissent être saisis", "Il remplace l'attribut type sur les champs"]),
        ],
    ))

    quizzes.append(quiz(
        "Structurer un article de blog complet",
        "Combiner les bons éléments sémantiques pour un article de blog HTML5.",
        [
            S("Quel élément englobe logiquement le contenu complet et autonome d'un article de blog ?",
              ["<article>", "<section>", "<div class='post'>", "<aside>"]),
            S("Quel élément interne à l'article afficherait typiquement le titre, l'auteur et la date de publication ?",
              ["<header>", "<title>", "<nav>", "<meta>"]),
            S("Quel élément serait approprié pour afficher une image illustrative avec sa légende dans l'article ?",
              ["<figure> avec <figcaption>", "<aside> seul", "<table>", "<img> seul sans figure"]),
            Sx("Quel élément serait pertinent pour afficher des liens vers des articles connexes en fin d'article, sans faire partie du contenu principal ?",
               ["<aside>", "<main>", "<header>", "<title>"], 0),
            T("Le <time> avec un attribut datetime est recommandé pour afficher la date de publication d'un article de façon machine-lisible.", True),
            T("Un article de blog HTML5 bien structuré ne peut contenir qu'un seul élément <p>.", False),
            M("Quels éléments sémantiques composent typiquement un article de blog bien structuré ?",
              ["<article>", "<header> local", "<footer> local", "<time>"],
              ["<frameset>", "<marquee>"]),
            M("Quelles affirmations sur la structuration d'un article sont correctes ?",
              ["Le header local de l'article peut contenir titre, auteur et date", "Le footer local de l'article peut contenir des tags ou des liens vers du contenu connexe"],
              ["L'article ne peut jamais contenir d'image", "L'article doit obligatoirement être unique sur toute la page"]),
        ],
    ))

    quizzes.append(quiz(
        "Le copier-coller et le presse-papier : notions HTML/JS de base",
        "Comprendre les évènements et attributs liés au presse-papier dans une page.",
        [
            S("Quels évènements JavaScript natifs sont déclenchés lors d'une action de copier, couper ou coller sur un élément ?",
              ["copy, cut, paste", "clipboard-copy, clipboard-cut, clipboard-paste", "ctrlc, ctrlx, ctrlv", "save, load, transfer"]),
            S("Quel attribut peut empêcher la sélection de texte par l'utilisateur via CSS (et non un attribut HTML pur) ?",
              ["La propriété CSS user-select:none", "L'attribut HTML noselect", "L'attribut HTML uncopyable", "L'attribut readonly seul"]),
            S("Quelle API JavaScript moderne permet d'écrire ou lire programmatique­ment dans le presse-papier du système, avec autorisation ?",
              ["Clipboard API (navigator.clipboard)", "Paste API", "Document.clipboard", "Window.copy"]),
            Sx("Pourquoi un site ne peut-il pas lire librement le presse-papier de l'utilisateur sans interaction ou permission explicite ?",
               ["Pour des raisons de sécurité et de confidentialité, afin d'éviter un accès non autorisé à des données sensibles copiées", "Parce que cela ralentirait le CSS", "Parce que le HTML l'interdit techniquement depuis toujours sans API", "Parce que cela nécessite un certificat SSL uniquement"], 0),
            T("Empêcher la sélection de texte avec CSS n'empêche pas nécessairement un utilisateur déterminé de récupérer le contenu par d'autres moyens (inspection du code, etc.).", True),
            T("L'évènement paste se déclenche automatiquement même sans action explicite de l'utilisateur.", False),
            M("Quelles affirmations sur le presse-papier et le web sont correctes ?",
              ["Les évènements copy/cut/paste peuvent être interceptés en JavaScript", "L'accès programmatique au presse-papier est soumis à des permissions de sécurité"],
              ["Tout site peut lire le presse-papier sans restriction", "Le HTML seul, sans JavaScript, peut intercepter ces évènements"]),
            M("Quels éléments seraient concernés par des évènements de copier-coller dans une page ?",
              ["Un champ de texte <input>", "Une zone <textarea>"],
              ["Une balise meta", "Le doctype du document"]),
        ],
    ))

    quizzes.append(quiz(
        "La balise noscript et la dégradation progressive",
        "Prévoir un contenu de repli quand JavaScript est indisponible.",
        [
            S("Quel élément HTML permet d'afficher un contenu alternatif lorsque JavaScript est désactivé ou non supporté par le navigateur ?",
              ["<noscript>", "<nojs>", "<fallback>", "<alt-script>"]),
            S("Où l'élément <noscript> peut-il être placé dans un document HTML ?",
              ["Dans <head> ou dans <body>, selon le contexte d'usage", "Uniquement dans <head>", "Uniquement à l'extérieur de <html>", "Uniquement dans <footer>"]),
            S("Qu'est-ce que la 'dégradation progressive' (progressive enhancement) en développement web ?",
              ["Une approche consistant à fournir une expérience de base fonctionnelle, puis à l'enrichir progressivement avec CSS et JavaScript", "Une technique de compression d'images", "Un protocole réseau", "Un format de fichier vidéo"]),
            Sx("Quel est l'intérêt principal de prévoir un contenu de repli avec <noscript> pour un site fortement dépendant de JavaScript ?",
               ["Offrir une information minimale ou une alternative aux utilisateurs sans JavaScript actif, plutôt qu'une page totalement vide", "Améliorer automatiquement la vitesse de chargement du JavaScript", "Remplacer entièrement le besoin de CSS", "Empêcher l'indexation de la page"], 0),
            T("Le contenu placé à l'intérieur de <noscript> n'est affiché par le navigateur que si JavaScript est désactivé ou non supporté.", True),
            T("L'élément <noscript> est obligatoire dans toute page HTML5 valide.", False),
            M("Quelles affirmations sur <noscript> sont correctes ?",
              ["Il fournit un contenu de repli pertinent sans JavaScript", "Son contenu est ignoré par le navigateur quand JavaScript est actif et supporté"],
              ["Il exécute du JavaScript alternatif", "Il remplace obligatoirement tout le body de la page"]),
            M("Quels principes sont associés à la dégradation progressive ou à l'amélioration progressive d'un site ?",
              ["Garantir une base fonctionnelle sans dépendre exclusivement du JavaScript", "Enrichir l'expérience pour les navigateurs capables de plus"],
              ["Exiger JavaScript pour afficher le moindre contenu textuel", "Ignorer totalement les utilisateurs sans JavaScript"]),
        ],
    ))

    quizzes.append(quiz(
        "Les media queries appliquées via la balise link",
        "Charger des feuilles de style conditionnellement selon le support d'affichage.",
        [
            S("Quel attribut de la balise <link rel='stylesheet'> permet d'appliquer la feuille de style uniquement sous certaines conditions d'affichage ?",
              ["media", "condition", "query", "device"]),
            S("Quelle valeur de l'attribut media cible spécifiquement l'impression du document, par exemple pour une mise en page différente ?",
              ["print", "printer", "paper", "output"]),
            S("Quelle syntaxe de media query ciblerait les écrans dont la largeur est d'au moins 768 pixels ?",
              ["(min-width: 768px)", "(width: 768px max)", "(screen-size: 768)", "(viewport: 768px)"]),
            Sx("Quel est l'avantage de séparer une feuille de style d'impression via media='print' plutôt que de tout gérer dans une seule feuille générale ?",
               ["Permettre de charger ou d'organiser un style dédié à l'impression sans affecter l'affichage écran", "Cela accélère uniquement le rendu JavaScript", "Cela est requis pour la validité HTML", "Cela remplace le besoin de balises meta viewport"], 0),
            T("On peut combiner plusieurs balises <link> avec des valeurs de media différentes pour charger des styles selon le contexte (écran, impression, etc.).", True),
            T("L'attribut media sur <link> empêche totalement le téléchargement de la feuille de style si la condition n'est pas remplie, dans tous les navigateurs et toutes circonstances.", False),
            M("Quelles valeurs ou syntaxes sont valides pour l'attribut media d'un <link> ?",
              ["screen", "print", "(min-width: 600px)"],
              ["mobile-only-mode", "high-resolution"]),
            M("Quelles affirmations sur les media queries liées à link sont correctes ?",
              ["Elles permettent d'adapter le style selon le type de média ou les caractéristiques de l'écran", "Elles peuvent cibler spécifiquement l'impression"],
              ["Elles remplacent les balises meta charset", "Elles sont incompatibles avec les feuilles de style CSS classiques"]),
        ],
    ))

    quizzes.append(quiz(
        "La gestion des erreurs réseau et image de remplacement",
        "Prévoir un comportement de repli quand une ressource ne charge pas.",
        [
            S("Que voit généralement l'utilisateur si une image référencée par <img src='...'> ne se charge pas ?",
              ["Une icône d'image cassée et le texte de l'attribut alt si présent", "La page entière refuse de s'afficher", "Un message d'erreur JavaScript bloquant", "Le favicon du site à la place"]),
            S("Quel évènement JavaScript peut être utilisé pour détecter qu'une image n'a pas pu être chargée, afin d'afficher une alternative ?",
              ["error (sur l'élément img)", "load uniquement", "fail-load", "broken"]),
            S("Pourquoi l'attribut alt reste-t-il utile même en cas d'échec de chargement d'une image ?",
              ["Parce qu'il fournit une description textuelle visible ou annoncée à la place de l'image manquante", "Parce qu'il recharge automatiquement l'image", "Parce qu'il change la taille de l'image", "Parce qu'il sert uniquement de nom de fichier"]),
            Sx("Quelle approche permettrait de remplacer dynamiquement une image cassée par une image de repli via JavaScript ?",
               ["Écouter l'évènement error sur l'image et modifier son attribut src vers une image de remplacement", "Modifier uniquement l'attribut alt", "Ajouter un attribut backup à l'image", "Utiliser uniquement du CSS sans JavaScript"], 0),
            T("L'attribut alt est annoncé par les lecteurs d'écran indépendamment du succès ou de l'échec du chargement réel de l'image.", True),
            T("Une image qui échoue à charger conserve toujours sa taille visuelle d'origine définie en CSS ou en attributs width/height.", True),
            M("Quelles affirmations sur la gestion des images manquantes sont correctes ?",
              ["L'évènement error permet de réagir programmatique­ment à un échec de chargement", "Un attribut alt pertinent améliore l'expérience même en cas d'échec"],
              ["Une image cassée bloque systématiquement tout le reste de la page", "L'attribut src est ignoré si alt est présent"]),
            M("Quelles pratiques aident à gérer les images potentiellement indisponibles ?",
              ["Fournir un attribut alt descriptif", "Prévoir une image de repli via JavaScript en cas d'erreur"],
              ["Omettre systématiquement l'attribut src", "Désactiver le CSS de la page entière"]),
        ],
    ))

    quizzes.append(quiz(
        "Les chemins relatifs et absolus dans les attributs src et href",
        "Bien référencer les ressources internes et externes d'un site.",
        [
            S("Qu'est-ce qu'un chemin relatif dans un attribut comme src ou href ?",
              ["Un chemin exprimé par rapport à l'emplacement du document courant", "Un chemin commençant toujours par https://", "Un chemin qui change selon la résolution d'écran", "Un chemin uniquement valide pour les images"]),
            S("Qu'est-ce qu'un chemin absolu dans ce contexte ?",
              ["Un chemin complet incluant le protocole et le domaine, ou partant de la racine du site avec un slash initial", "Un chemin toujours plus court qu'un chemin relatif", "Un chemin qui ne fonctionne que sur le même appareil", "Un chemin réservé aux balises meta"]),
            S("Que représente '../' au début d'un chemin relatif ?",
              ["Remonter d'un niveau dans l'arborescence de dossiers par rapport au document courant", "Aller à la racine absolue du site", "Aller directement au domaine externe", "Une erreur de syntaxe systématique"]),
            Sx("Quel avantage présente un chemin commençant par un seul slash, comme '/images/photo.jpg', par rapport à la racine du site ?",
               ["Il reste valide quel que soit le sous-dossier où se trouve la page actuelle, car il part toujours de la racine du domaine", "Il fonctionne uniquement en local", "Il est plus rapide à charger", "Il remplace le besoin de l'attribut alt"], 0),
            T("Un lien avec un chemin relatif peut se rompre si le fichier HTML est déplacé dans un autre dossier sans ajuster le chemin.", True),
            T("Un chemin absolu commençant par https:// pointe nécessairement vers le même domaine que la page courante.", False),
            M("Quelles affirmations sur les chemins relatifs et absolus sont correctes ?",
              ["Les chemins relatifs dépendent de l'emplacement du fichier courant", "Les chemins absolus incluent souvent le protocole et le domaine complet"],
              ["Les deux types de chemin sont strictement interchangeables sans risque", "Les chemins relatifs fonctionnent uniquement pour les images"]),
            M("Quels éléments HTML utilisent couramment des attributs avec des chemins relatifs ou absolus ?",
              ["<img src>", "<a href>", "<link href>"],
              ["<meta charset>", "<title>"]),
        ],
    ))

    quizzes.append(quiz(
        "Le contenu de remplacement des éléments embed et object",
        "Comprendre les anciennes méthodes d'intégration de contenu externe.",
        [
            S("Quel élément historique permettait d'intégrer un contenu externe via un plugin, comme un fichier Flash ou PDF ?",
              ["<embed> ou <object>", "<iframe> uniquement", "<plugin>", "<external>"]),
            S("Quel attribut de <object> précise le type MIME de la ressource intégrée, par exemple application/pdf ?",
              ["type", "src uniquement", "mime", "format"]),
            S("Quel élément peut être placé à l'intérieur de <object> pour fournir un contenu de remplacement si la ressource ne peut être affichée ?",
              ["Un contenu de repli directement entre les balises ouvrante et fermante de object", "Un attribut fallback obligatoire", "Un élément <noembed> uniquement", "Aucun contenu de repli n'est possible"]),
            Sx("Pourquoi l'usage de <embed>/<object> pour des plugins comme Flash a-t-il fortement décliné avec l'avènement de HTML5 ?",
               ["Parce que des éléments natifs comme <video>, <audio> et <canvas> couvrent désormais nativement de nombreux cas d'usage sans plugin tiers", "Parce que ces éléments sont devenus illégaux", "Parce qu'ils ne supportent aucun attribut", "Parce que les navigateurs ont cessé d'analyser le HTML"], 0),
            T("L'élément <object> peut encore être utilisé aujourd'hui pour intégrer certains contenus comme des PDF, selon le support du navigateur.", True),
            T("L'élément <embed> est un élément de type bloc qui ne peut jamais être stylisé avec CSS.", False),
            M("Quelles affirmations sur <object>/<embed> sont correctes ?",
              ["Ils permettent d'intégrer des ressources externes variées", "<object> peut proposer un contenu de secours en cas d'échec"],
              ["Ils ont totalement disparu des spécifications HTML5", "Ils remplacent obligatoirement <img>"]),
            M("Quels éléments HTML5 natifs ont réduit la dépendance aux plugins historiques comme Flash ?",
              ["<video>", "<audio>", "<canvas>"],
              ["<embed>", "<object>"]),
        ],
    ))

    quizzes.append(quiz(
        "Web components et templates : approfondissement",
        "Aller plus loin sur le cycle de vie des éléments personnalisés.",
        [
            S("Quel est le nom de la méthode de cycle de vie appelée lorsqu'un élément personnalisé (custom element) est inséré dans le DOM ?",
              ["connectedCallback", "onMount", "init", "onInsert"]),
            S("Quelle API permet de définir un nouvel élément personnalisé reconnu par le navigateur, par exemple customElements.define ?",
              ["CustomElementRegistry (via customElements.define)", "DocumentRegistry", "ElementFactory", "TagBuilder"]),
            S("Quel est l'intérêt principal d'isoler le style d'un composant via le Shadow DOM ?",
              ["Éviter que les styles CSS du composant n'affectent ou ne soient affectés par le reste de la page", "Accélérer le chargement des images", "Améliorer le SEO automatiquement", "Remplacer le besoin de JavaScript"]),
            Sx("Quelle méthode de cycle de vie d'un élément personnalisé est appelée lorsqu'il est retiré du DOM ?",
               ["disconnectedCallback", "removedCallback", "onUnmount", "destroy"], 0),
            T("Un nom de balise personnalisée valide pour un Web Component doit contenir au moins un tiret, par exemple mon-composant.", True),
            T("Le Shadow DOM empêche définitivement tout style global de la page d'influencer le composant, sans aucune exception possible.", False),
            M("Quelles méthodes font partie du cycle de vie standard d'un élément personnalisé ?",
              ["connectedCallback", "disconnectedCallback", "attributeChangedCallback"],
              ["onPageLoad", "onWindowResize"]),
            M("Quelles affirmations sur les Web Components sont correctes ?",
              ["Ils permettent de créer des éléments HTML réutilisables et encapsulés", "Ils s'appuient sur des APIs natives du navigateur sans framework obligatoire"],
              ["Ils nécessitent obligatoirement React ou Vue pour fonctionner", "Ils remplacent les balises meta SEO"]),
        ],
    ))

    quizzes.append(quiz(
        "Les boutons de navigation native dans les formulaires multi-étapes",
        "Gérer la navigation entre étapes sans recharger toute la page.",
        [
            S("Quel attribut permettrait à un bouton soumettant un formulaire de cibler une URL d'action différente de celle définie sur le form lui-même ?",
              ["formaction sur le bouton", "action sur le bouton", "target sur le bouton uniquement", "href sur le bouton"]),
            S("Quel attribut sur un bouton submit permettrait de changer temporairement la méthode HTTP utilisée pour cette soumission spécifique ?",
              ["formmethod", "method-override", "httpmethod", "formhttp"]),
            S("Quel attribut sur un bouton submit permettrait de désactiver la validation HTML5 uniquement pour cette soumission, par exemple pour un bouton 'Enregistrer comme brouillon' ?",
              ["formnovalidate", "novalidate-button", "skipvalidation", "ignore-required"]),
            Sx("Pourquoi ces attributs form* (formaction, formmethod, formnovalidate) sur les boutons sont-ils utiles dans un formulaire à plusieurs boutons de soumission ?",
               ["Ils permettent de personnaliser le comportement de soumission selon le bouton cliqué, sans dupliquer tout le formulaire", "Ils sont requis pour que le formulaire fonctionne du tout", "Ils remplacent l'attribut name du formulaire", "Ils s'appliquent uniquement aux liens, pas aux boutons"], 0),
            T("Les attributs formaction, formmethod et formnovalidate s'appliquent uniquement aux boutons de type submit, pas aux boutons de type button.", True),
            T("formnovalidate désactive la validation HTML5 pour tout le site de façon permanente une fois cliqué.", False),
            M("Quels attributs permettent de personnaliser la soumission d'un formulaire selon le bouton cliqué ?",
              ["formaction", "formmethod", "formnovalidate"],
              ["colspan", "scope"]),
            M("Quelles affirmations sur les formulaires à plusieurs boutons de soumission sont correctes ?",
              ["Chaque bouton peut potentiellement avoir un comportement de soumission distinct", "Cela évite de dupliquer le formulaire pour chaque action possible"],
              ["Un formulaire ne peut avoir qu'un seul bouton submit au maximum", "Les attributs form* nécessitent obligatoirement JavaScript pour fonctionner"]),
        ],
    ))

    return quizzes
