from helpers_html import S, Sx, M, T, quiz

def get_quizzes():
    quizzes = []

    quizzes.append(quiz(
        "Les éléments de média : audio",
        "Intégrer du son natif avec l'élément audio et ses sources.",
        [
            S("Quel élément HTML5 permet d'intégrer un fichier audio natif sans plugin externe ?",
              ["<audio>", "<sound>", "<music>", "<embed>"]),
            S("Quel attribut de <audio> affiche les contrôles de lecture (play, pause, volume) ?",
              ["controls", "visible", "player", "show"]),
            S("Quel attribut permet de démarrer automatiquement la lecture d'un audio à l'ouverture de la page ?",
              ["autoplay", "autostart", "play", "start"]),
            Sx("Quel élément enfant de <audio> permet de proposer plusieurs formats de fichier (mp3, ogg) ?",
               ["<source>", "<track>", "<format>", "<media>"], 0),
            T("L'attribut loop sur <audio> permet de relancer automatiquement la lecture en boucle.", True),
            T("Le navigateur ignore systématiquement l'attribut autoplay si le son n'est pas coupé (muted), sur de nombreux navigateurs modernes.", True),
            M("Quels attributs sont valides sur l'élément <audio> ?",
              ["controls", "loop", "muted"],
              ["volume-level", "format"]),
            M("Quelles affirmations sur l'élément <source> dans <audio> sont correctes ?",
              ["Il permet de spécifier l'attribut type (ex : audio/mpeg)", "Le navigateur choisit la première source qu'il sait lire"],
              ["Il est obligatoire même si une seule source est utilisée via src sur <audio>", "Il remplace l'attribut controls"]),
        ],
    ))

    quizzes.append(quiz(
        "Les éléments de média : video, source et track",
        "Intégrer des vidéos accessibles avec sous-titres.",
        [
            S("Quel élément HTML5 permet d'intégrer une vidéo native ?",
              ["<video>", "<movie>", "<film>", "<media>"]),
            S("Quel élément permet d'ajouter des sous-titres ou une piste de texte synchronisée à une vidéo ?",
              ["<track>", "<subtitle>", "<caption>", "<text>"]),
            S("Quel attribut de <track> définit le type de piste, par exemple des sous-titres ?",
              ["kind", "type", "category", "role"]),
            Sx("Quel attribut de <video> définit une image affichée avant le démarrage de la lecture ?",
               ["poster", "thumbnail", "preview", "cover"], 0),
            T("L'attribut muted est souvent nécessaire pour permettre l'autoplay d'une vidéo sur les navigateurs modernes.", True),
            T("L'élément <track> ne peut être utilisé qu'avec <video>, jamais avec <audio>.", False),
            M("Quelles valeurs sont des valeurs valides de l'attribut kind sur <track> ?",
              ["subtitles", "captions", "descriptions"],
              ["audio", "video"]),
            M("Quelles affirmations sur <video> sont correctes ?",
              ["L'attribut controls affiche l'interface de lecture native", "On peut fournir plusieurs <source> pour la compatibilité"],
              ["Il nécessite obligatoirement un plugin Flash", "L'attribut autoplay garantit le son activé"]),
        ],
    ))

    quizzes.append(quiz(
        "L'élément iframe",
        "Intégrer du contenu externe dans une page avec des cadres en ligne.",
        [
            S("Quel élément permet d'intégrer une autre page web à l'intérieur de la page courante ?",
              ["<iframe>", "<frame>", "<embed>", "<include>"]),
            S("Quel attribut de <iframe> définit l'URL de la page à intégrer ?",
              ["src", "href", "url", "link"]),
            S("Quel attribut permet de fournir un texte alternatif décrivant le contenu d'un iframe pour l'accessibilité ?",
              ["title", "alt", "aria-label uniquement", "desc"]),
            Sx("Quel attribut permet de restreindre les permissions et fonctionnalités d'un iframe (scripts, formulaires, popups) ?",
               ["sandbox", "restrict", "limit", "secure"], 0),
            T("L'attribut loading='lazy' sur un iframe permet de différer son chargement jusqu'à ce qu'il approche du viewport.", True),
            T("Un iframe peut uniquement afficher des pages issues du même domaine que la page parente.", False),
            M("Quels attributs sont valides sur l'élément <iframe> ?",
              ["src", "title", "width"],
              ["embed-type", "frame-src-list"]),
            M("Quelles affirmations sur l'élément <title> appliqué à un iframe sont correctes ?",
              ["Il améliore l'accessibilité pour les lecteurs d'écran", "Il décrit le contenu ou la fonction de l'iframe"],
              ["Il est obligatoire pour que l'iframe s'affiche", "Il remplace l'attribut src"]),
        ],
    ))

    quizzes.append(quiz(
        "La balise head et le SEO de base",
        "Configurer les métadonnées essentielles pour le référencement.",
        [
            S("Quel élément définit le titre de la page affiché dans les résultats de recherche et l'onglet ?",
              ["<title>", "<head>", "<meta>", "<h1>"]),
            S("Quelle balise meta définit l'encodage de caractères utilisé par le document ?",
              ['<meta charset="UTF-8">', '<meta encoding="UTF-8">', '<meta lang="UTF-8">', '<meta type="UTF-8">']),
            S("Quelle balise meta contrôle l'affichage responsive sur les appareils mobiles ?",
              ['<meta name="viewport">', '<meta name="mobile">', '<meta name="responsive">', '<meta name="screen">']),
            Sx("Quelle balise meta fournit une description de la page souvent affichée dans les résultats de recherche ?",
               ['<meta name="description">', '<meta name="summary">', '<meta name="seo">', '<meta name="keywords">'], 0),
            T("L'élément <title> doit être placé à l'intérieur de <head>, pas dans <body>.", True),
            T("Un document HTML peut avoir plusieurs éléments <title> sans conséquence sur le SEO.", False),
            M("Quels éléments font partie des bonnes pratiques SEO de base dans <head> ?",
              ["<title> unique et descriptif", "<meta name='description'>", "balise canonique <link rel='canonical'>"],
              ["<meta name='animation'>", "<script async> obligatoire"]),
            M("Quelles affirmations sur le favicon sont correctes ?",
              ["Il se déclare via <link rel='icon' href='...'>", "Il s'affiche dans l'onglet du navigateur"],
              ["Il doit obligatoirement être au format .docx", "Il remplace la balise <title>"]),
        ],
    ))

    quizzes.append(quiz(
        "Charset, viewport et favicon en détail",
        "Approfondir les balises meta techniques indispensables.",
        [
            S("Quel encodage de caractères est aujourd'hui recommandé pour les pages web modernes ?",
              ["UTF-8", "ASCII", "ISO-8859-1", "UTF-16"]),
            S("Quelle valeur de l'attribut content du viewport définit la largeur égale à celle de l'appareil ?",
              ["width=device-width", "width=100%", "width=auto", "width=screen"]),
            S("Quel attribut de <link> indique la relation entre le document et la ressource liée, comme 'icon' pour un favicon ?",
              ["rel", "type", "href", "name"]),
            Sx("Quelle est la conséquence d'une absence de balise meta viewport sur un site consulté depuis un mobile ?",
               ["La page peut s'afficher mal proportionnée, comme sur un écran de bureau réduit", "Le navigateur refuse de charger la page", "Le favicon ne s'affiche plus", "Le titre de la page disparaît"], 0),
            T("La balise meta charset doit idéalement être déclarée le plus tôt possible dans <head>, avant les autres balises qui contiennent du texte.", True),
            T("Un favicon doit obligatoirement être au format .ico, aucun autre format n'est supporté.", False),
            M("Quels attributs peut-on trouver sur une balise <link rel='icon'> ?",
              ["href", "type", "sizes"],
              ["alt", "loading"]),
            M("Quelles affirmations sur la balise meta viewport sont correctes ?",
              ["Elle aide à l'affichage adaptatif sur mobile", "On y trouve souvent initial-scale=1"],
              ["Elle définit l'encodage de caractères", "Elle remplace les media queries CSS"]),
        ],
    ))

    quizzes.append(quiz(
        "Accessibilité : ARIA et rôles",
        "Renforcer l'accessibilité avec les attributs ARIA quand le HTML sémantique ne suffit pas.",
        [
            S("Que signifie l'acronyme ARIA dans le contexte du web ?",
              ["Accessible Rich Internet Applications", "Advanced Responsive Interface Architecture", "Automated Rendering Interface API", "Accessible Resource Identifier Attribute"]),
            S("Quel attribut ARIA définit explicitement le rôle fonctionnel d'un élément pour les technologies d'assistance ?",
              ["role", "type", "aria-type", "function"]),
            S("Quel attribut ARIA fournit un nom accessible à un élément lorsqu'aucun texte visible n'est disponible ?",
              ["aria-label", "title-aria", "alt-label", "aria-name"]),
            Sx("Quelle est la règle d'or recommandée concernant ARIA et le HTML sémantique natif ?",
               ["Préférer un élément HTML sémantique natif plutôt qu'ajouter un rôle ARIA sur un élément générique", "Toujours ajouter ARIA même quand un élément natif existe", "ARIA remplace entièrement le HTML sémantique", "ARIA n'est utile que pour les images"], 0),
            T("L'attribut aria-hidden='true' masque un élément aux technologies d'assistance tout en le laissant visible visuellement.", True),
            T("Ajouter role='button' sur un <div> le rend automatiquement focusable au clavier sans attribut supplémentaire.", False),
            M("Quels attributs sont des attributs ARIA valides ?",
              ["aria-label", "aria-hidden", "aria-expanded"],
              ["aria-color", "aria-fontsize"]),
            M("Quelles affirmations sur les rôles ARIA sont correctes ?",
              ["Ils peuvent décrire l'état d'un composant (ex : aria-expanded)", "Ils complètent le HTML quand la sémantique native est insuffisante"],
              ["Ils modifient l'apparence visuelle d'un élément", "Ils sont obligatoires sur chaque élément HTML"]),
        ],
    ))

    quizzes.append(quiz(
        "Accessibilité : alt, tabindex et labels",
        "Maîtriser les bases concrètes de l'accessibilité au clavier et pour les lecteurs d'écran.",
        [
            S("Quel attribut permet de rendre un élément focusable au clavier même s'il ne l'est pas nativement ?",
              ["tabindex", "focusable", "keynav", "accesskey"]),
            S("Quelle valeur de tabindex retire un élément de l'ordre de tabulation naturel tout en le laissant focusable via JavaScript ?",
              ["-1", "0", "1", "none"]),
            S("Quel attribut texte alternatif est indispensable sur une image porteuse de sens ?",
              ["alt", "title", "name", "desc"]),
            Sx("Pourquoi associer un <label> à chaque champ de formulaire est important pour l'accessibilité ?",
               ["Cela permet aux lecteurs d'écran d'annoncer la fonction du champ", "Cela améliore uniquement l'apparence visuelle", "Cela accélère le chargement de la page", "Cela remplace l'attribut required"], 0),
            T("La valeur tabindex='0' insère l'élément dans l'ordre naturel de tabulation du document.", True),
            T("Utiliser des valeurs positives élevées de tabindex partout est une bonne pratique recommandée.", False),
            M("Quelles pratiques améliorent l'accessibilité au clavier d'une page ?",
              ["Utiliser des éléments interactifs natifs (button, a)", "Gérer un focus visible clairement", "Respecter un ordre de tabulation logique"],
              ["Désactiver le focus visuel par défaut sans alternative", "Utiliser uniquement des <div> cliquables sans rôle"]),
            M("Quelles affirmations sur l'attribut alt sont correctes ?",
              ["Une image décorative peut avoir alt=''", "Une image informative doit décrire son contenu ou sa fonction"],
              ["alt est uniquement utile pour le référencement, jamais pour l'accessibilité", "alt doit toujours contenir le nom du fichier image"]),
        ],
    ))

    quizzes.append(quiz(
        "Les attributs globaux : id, class, data-* et style",
        "Comprendre les attributs utilisables sur la quasi-totalité des éléments HTML.",
        [
            S("Quel attribut global identifie de façon unique un élément dans tout le document ?",
              ["id", "class", "name", "key"]),
            S("Quel attribut global permet d'appliquer un même style ou comportement à plusieurs éléments ?",
              ["class", "id", "group", "tag"]),
            S("Quel préfixe d'attribut permet de stocker des données personnalisées directement sur un élément HTML ?",
              ["data-", "custom-", "x-", "meta-"]),
            Sx("Quel attribut global permet d'appliquer du CSS directement en ligne sur un élément ?",
               ["style", "css", "design", "format"], 0),
            T("Un attribut id doit être unique dans tout le document HTML, alors qu'une class peut être réutilisée sur plusieurs éléments.", True),
            T("Les attributs data-* personnalisés provoquent une erreur de validation HTML s'ils ne sont pas déclarés dans une spécification officielle.", False),
            M("Quels attributs sont considérés comme des attributs globaux applicables à presque tout élément HTML ?",
              ["id", "class", "title", "lang"],
              ["href", "src"]),
            M("Quelles affirmations sur les attributs data-* sont correctes ?",
              ["Ils sont accessibles en JavaScript via dataset", "Ils permettent de stocker des informations sans balises supplémentaires"],
              ["Ils ne peuvent contenir que des nombres", "Ils sont réservés aux éléments de formulaire"]),
        ],
    ))

    quizzes.append(quiz(
        "Éléments block versus inline",
        "Différencier le comportement d'affichage par défaut des éléments HTML.",
        [
            S("Quel type d'élément occupe par défaut toute la largeur disponible et commence sur une nouvelle ligne ?",
              ["Élément de type bloc (block)", "Élément en ligne (inline)", "Élément vide", "Élément flottant"]),
            S("Quel élément est un exemple typique d'élément en ligne (inline) ?",
              ["<span>", "<div>", "<p>", "<section>"]),
            S("Quel élément est un exemple typique d'élément de type bloc ?",
              ["<div>", "<span>", "<strong>", "<em>"]),
            Sx("Quelle propriété CSS permet de changer le comportement d'affichage par défaut d'un élément (par exemple de inline à block) ?",
               ["display", "position", "float", "visibility"], 0),
            T("Un élément en ligne (inline) comme <span> ne provoque pas de retour à la ligne avant ou après lui par défaut.", True),
            T("Un élément de type bloc comme <div> ne peut jamais contenir un élément en ligne comme <span>.", False),
            M("Quels éléments sont des éléments en ligne par défaut ?",
              ["<span>", "<a>", "<strong>"],
              ["<div>", "<section>"]),
            M("Quelles affirmations sur les éléments de type bloc sont correctes ?",
              ["Ils peuvent contenir d'autres éléments de bloc ou en ligne", "Ils acceptent généralement les propriétés width et height en CSS"],
              ["Ils ne peuvent jamais avoir de marges", "Ils sont toujours affichés en gras par défaut"]),
        ],
    ))

    quizzes.append(quiz(
        "Les éléments vides (void elements)",
        "Identifier les balises HTML qui ne possèdent pas de balise fermante.",
        [
            S("Comment appelle-t-on un élément HTML qui ne peut pas avoir de contenu ni de balise fermante ?",
              ["Élément vide (void element)", "Élément orphelin", "Élément fantôme", "Élément nul"]),
            S("Lequel de ces éléments est un élément vide ?",
              ["<br>", "<p>", "<div>", "<span>"]),
            S("Lequel de ces éléments est également un élément vide couramment utilisé pour les images ?",
              ["<img>", "<picture>", "<figure>", "<a>"]),
            Sx("Quel élément vide insère un saut de ligne à l'intérieur d'un bloc de texte ?",
               ["<br>", "<hr>", "<p>", "<wbr>"], 0),
            T("En HTML5, écrire <br/> avec un slash de fermeture ou <br> sans slash sont tous deux valides.", True),
            T("L'élément <hr> représente une rupture thématique entre deux paragraphes, généralement affichée comme une ligne horizontale.", True),
            M("Lesquels des éléments suivants sont des éléments vides en HTML ?",
              ["<input>", "<meta>", "<link>"],
              ["<label>", "<textarea>"]),
            M("Quelles affirmations sur les éléments vides sont correctes ?",
              ["Ils ne peuvent pas avoir de contenu enfant", "Ils peuvent posséder des attributs comme n'importe quel élément"],
              ["Ils nécessitent toujours une balise fermante explicite en HTML5", "Ils ne peuvent jamais avoir d'attribut src ou href"]),
        ],
    ))

    quizzes.append(quiz(
        "Entités HTML et caractères spéciaux",
        "Afficher correctement les caractères réservés et spéciaux dans une page.",
        [
            S("Quelle entité HTML permet d'afficher le caractère < sans qu'il soit interprété comme une balise ?",
              ["&lt;", "&gt;", "&amp;", "&quot;"]),
            S("Quelle entité HTML permet d'afficher le caractère > littéralement ?",
              ["&gt;", "&lt;", "&apos;", "&nbsp;"]),
            S("Quelle entité HTML permet d'afficher le caractère & littéralement ?",
              ["&amp;", "&and;", "&et;", "&amper;"]),
            Sx("Quelle entité HTML insère une espace insécable, empêchant un retour à la ligne à cet endroit ?",
               ["&nbsp;", "&space;", "&sp;", "&blank;"], 0),
            T("Les entités HTML peuvent être écrites sous forme de nom (&amp;) ou sous forme numérique (&#38;).", True),
            T("Il est obligatoire d'échapper le caractère & avec une entité dans tout texte HTML, même en dehors de tout contexte ambigu.", False),
            M("Quelles entités HTML sont correctement nommées et reconnues ?",
              ["&copy;", "&euro;", "&quot;"],
              ["&dollar;", "&percent2;"]),
            M("Quelles affirmations sur les entités HTML sont correctes ?",
              ["Elles permettent d'afficher des caractères réservés du langage HTML", "Elles peuvent représenter des symboles comme © ou €"],
              ["Elles ne fonctionnent que dans les attributs, jamais dans le texte", "Elles remplacent l'encodage UTF-8"]),
        ],
    ))

    quizzes.append(quiz(
        "Les commentaires HTML",
        "Documenter son code source sans impacter le rendu visuel de la page.",
        [
            S("Quelle syntaxe permet d'écrire un commentaire en HTML ?",
              ["<!-- commentaire -->", "// commentaire", "/* commentaire */", "# commentaire"]),
            S("Un commentaire HTML est-il visible dans le rendu affiché par le navigateur ?",
              ["Non, il est ignoré lors de l'affichage", "Oui, en italique", "Oui, en gris clair", "Oui, mais seulement sur mobile"]),
            S("Un commentaire HTML peut-il être vu dans le code source de la page si on l'inspecte ?",
              ["Oui, il reste visible dans le code source", "Non, il est totalement supprimé avant l'envoi", "Seulement si JavaScript est désactivé", "Seulement en mode développeur"]),
            Sx("Que se passe-t-il si l'on insère accidentellement la séquence '--' à l'intérieur du texte d'un commentaire HTML ?",
               ["Cela peut provoquer un comportement de parsing invalide ou inattendu", "Rien, c'est totalement sans risque", "Le commentaire devient automatiquement un titre", "Le navigateur supprime toute la page"], 0),
            T("Les commentaires HTML peuvent s'étendre sur plusieurs lignes.", True),
            T("On peut imbriquer un commentaire HTML à l'intérieur d'un autre commentaire HTML sans problème.", False),
            M("Quelles utilisations légitimes des commentaires HTML existent ?",
              ["Désactiver temporairement un bloc de code pour le débogage", "Documenter une section complexe du code"],
              ["Stocker des mots de passe car ils sont invisibles", "Exécuter du JavaScript caché"]),
            M("Quelles affirmations sur les commentaires HTML sont correctes ?",
              ["Ils commencent par <!-- et se terminent par -->", "Ils n'affectent pas le rendu visuel de la page"],
              ["Ils sont exécutés comme du code côté serveur", "Ils remplacent les balises meta description pour le SEO"]),
        ],
    ))

    return quizzes
