from helpers_html import S, Sx, M, T, quiz

def get_quizzes():
    quizzes = []

    quizzes.append(quiz(
        "Texte en ligne : strong, em, small, sub et sup",
        "Apporter du sens supplémentaire à des portions de texte en ligne.",
        [
            S("Quel élément indique une importance forte du texte, généralement affiché en gras ?",
              ["<strong>", "<b>", "<important>", "<bold>"]),
            S("Quel élément indique une emphase, un accent de prononciation, généralement affiché en italique ?",
              ["<em>", "<i>", "<italic>", "<accent>"]),
            S("Quel élément affiche du texte en indice, par exemple pour une formule chimique comme H2O ?",
              ["<sub>", "<sup>", "<small>", "<index>"]),
            Sx("Quel élément affiche du texte en exposant, par exemple pour une puissance mathématique comme x²?",
               ["<sup>", "<sub>", "<small>", "<power>"], 0),
            T("<strong> porte une signification sémantique d'importance, alors que <b> est purement visuel sans signification particulière.", True),
            T("L'élément <small> sert uniquement à réduire la taille de police sans aucune signification sémantique, comme une mention légale.", False),
            M("Quels éléments apportent une signification sémantique au texte, au-delà du simple style visuel ?",
              ["<strong>", "<em>", "<mark>"],
              ["<b>", "<i>"]),
            M("Quelles affirmations sur <em> et <strong> sont correctes ?",
              ["Ils peuvent être imbriqués pour cumuler les niveaux d'emphase ou d'importance", "Leur rendu par défaut est respectivement italique et gras"],
              ["Ils sont strictement interchangeables avec <i> et <b> en termes de sens", "Ils ne peuvent être utilisés que dans un titre"]),
        ],
    ))

    quizzes.append(quiz(
        "Le bouton button et ses types",
        "Distinguer les usages des différents types de bouton en formulaire.",
        [
            S("Quel élément crée un bouton cliquable polyvalent dans une page ou un formulaire ?",
              ["<button>", "<btn>", "<click>", "<action>"]),
            S("Quelle valeur de l'attribut type sur <button> déclenche la soumission du formulaire englobant ?",
              ["submit", "send", "go", "post"]),
            S("Quelle valeur de l'attribut type sur <button> n'effectue aucune action native par défaut, utile pour du JavaScript personnalisé ?",
              ["button", "none", "custom", "script"]),
            Sx("Quel attribut booléen permet de désactiver un bouton, empêchant son utilisation par l'utilisateur ?",
               ["disabled", "inactive", "readonly", "locked"], 0),
            T("Si l'attribut type est omis sur un <button> à l'intérieur d'un <form>, le comportement par défaut est généralement submit.", True),
            T("Un <button> ne peut contenir que du texte brut, jamais d'image ni d'icône.", False),
            M("Quelles valeurs sont valides pour l'attribut type d'un <button> ?",
              ["submit", "reset", "button"],
              ["click", "action"]),
            M("Quelles affirmations sur <button> sont correctes ?",
              ["Il est focusable au clavier nativement", "Il peut contenir des éléments enfants comme <span> ou une image"],
              ["Il nécessite obligatoirement un attribut onclick pour fonctionner", "Il ne peut jamais être utilisé hors d'un formulaire"]),
        ],
    ))

    quizzes.append(quiz(
        "Préformaté et code source : pre, code, kbd, samp",
        "Afficher du texte technique, du code ou des séquences de touches.",
        [
            S("Quel élément conserve les espaces et retours à la ligne du texte tel qu'il a été écrit dans le code source ?",
              ["<pre>", "<code>", "<plain>", "<raw>"]),
            S("Quel élément indique sémantiquement qu'un fragment de texte représente du code informatique ?",
              ["<code>", "<pre>", "<script>", "<source>"]),
            S("Quel élément représente une touche ou une combinaison de touches à saisir au clavier ?",
              ["<kbd>", "<key>", "<input-key>", "<press>"]),
            Sx("Quel élément représente la sortie ou le résultat produit par un programme ou un script ?",
               ["<samp>", "<output>", "<result>", "<code>"], 0),
            T("Combiner <pre> et <code> ensemble est une pratique courante pour afficher un bloc de code multi-lignes correctement formaté.", True),
            T("L'élément <code> change automatiquement la police en une police à chasse fixe (monospace) par défaut dans la plupart des navigateurs.", True),
            M("Quels éléments servent à représenter du contenu technique ou du code ?",
              ["<code>", "<pre>", "<kbd>"],
              ["<cite>", "<mark>"]),
            M("Quelles affirmations sur <pre> sont correctes ?",
              ["Il préserve les espaces multiples et les retours à la ligne du texte source", "Il est souvent utilisé conjointement avec <code> pour des extraits de programme"],
              ["Il convertit automatiquement le texte en majuscules", "Il interdit toute mise en forme CSS supplémentaire"]),
        ],
    ))

    quizzes.append(quiz(
        "Listes imbriquées et structuration avancée",
        "Construire des structures de listes complexes et hiérarchiques.",
        [
            S("Comment crée-t-on une sous-liste à l'intérieur d'un élément de liste existant ?",
              ["En plaçant une nouvelle <ul> ou <ol> à l'intérieur de l'élément <li> parent", "En ajoutant l'attribut nested à li", "En utilisant l'élément <sublist>", "Ce n'est pas possible en HTML"]),
            S("Quel attribut de <ol> inverse l'ordre de numérotation, du plus grand au plus petit nombre ?",
              ["reversed", "invert", "desc", "order=desc"]),
            S("Quel attribut de <li> permet de définir manuellement la valeur numérique de cet élément dans une liste ordonnée ?",
              ["value", "number", "index", "count"]),
            Sx("Quel élément serait le plus approprié pour présenter une table des matières avec sous-sections numérotées ?",
               ["Des <ol> imbriqués dans des <li>", "Une seule longue liste <ul> à plat", "Un <table> uniquement", "Un <dl> uniquement"], 0),
            T("Un élément <li> peut contenir plusieurs paragraphes <p> ainsi qu'une sous-liste complète.", True),
            T("L'attribut type sur <ol> permettait historiquement de choisir le style de numérotation (chiffres romains, lettres), bien que CSS list-style-type soit désormais préféré.", True),
            M("Quels attributs sont valides sur l'élément <ol> ou ses <li> ?",
              ["reversed sur ol", "start sur ol", "value sur li"],
              ["bullet sur li", "indent sur ol"]),
            M("Quelles affirmations sur les listes imbriquées sont correctes ?",
              ["Chaque niveau d'imbrication doit rester un enfant valide d'un <li>", "Elles permettent de représenter des hiérarchies, comme un sommaire"],
              ["Elles sont interdites par la spécification HTML5", "Elles nécessitent obligatoirement du JavaScript pour fonctionner"]),
        ],
    ))

    quizzes.append(quiz(
        "Les types d'input HTML5 avancés : range, color, file",
        "Découvrir des contrôles de saisie HTML5 spécialisés.",
        [
            S("Quel type d'input affiche un curseur glissant pour choisir une valeur numérique dans une plage ?",
              ['type="range"', 'type="number"', 'type="slider"', 'type="scale"']),
            S("Quel type d'input affiche un sélecteur de couleur natif ?",
              ['type="color"', 'type="palette"', 'type="rgb"', 'type="paint"']),
            S("Quel type d'input permet à l'utilisateur de sélectionner un ou plusieurs fichiers depuis son appareil ?",
              ['type="file"', 'type="upload"', 'type="document"', 'type="attach"']),
            Sx("Quel attribut sur un input de type file permet d'autoriser la sélection de plusieurs fichiers à la fois ?",
               ["multiple", "many", "files", "batch"], 0),
            T("L'attribut accept sur un input de type file permet de restreindre les types de fichiers proposés, par exemple accept='image/*'.", True),
            T("Un input de type range affiche par défaut une valeur numérique textuelle visible sans CSS ni JavaScript additionnel.", False),
            M("Quels types d'input HTML5 retournent une valeur sous forme de chaîne formatée spécifique (date, couleur, etc.) ?",
              ["date", "color", "time"],
              ["submit", "button"]),
            M("Quelles affirmations sur l'input de type file sont correctes ?",
              ["Il peut être stylisé en CSS bien que son apparence native varie selon le navigateur", "L'attribut accept aide à filtrer les fichiers proposés par le système"],
              ["Il transmet automatiquement le contenu du fichier dans l'attribut value en texte", "Il fonctionne uniquement avec la méthode GET"]),
        ],
    ))

    quizzes.append(quiz(
        "Placeholder, autofocus et autocomplete",
        "Améliorer l'expérience de saisie des formulaires avec des attributs dédiés.",
        [
            S("Quel attribut affiche un texte d'exemple grisé à l'intérieur d'un champ vide, qui disparaît à la saisie ?",
              ["placeholder", "hint", "example", "default"]),
            S("Quel attribut met automatiquement le focus sur un champ dès le chargement de la page ?",
              ["autofocus", "focus", "active", "default-focus"]),
            S("Quel attribut permet ou empêche la suggestion de valeurs précédemment saisies par le navigateur ?",
              ["autocomplete", "autofill", "suggest", "remember"]),
            Sx("Pourquoi le placeholder ne doit-il pas remplacer un véritable élément <label> ?",
               ["Le texte du placeholder disparaît dès la saisie et n'est pas toujours bien interprété par les lecteurs d'écran", "Le placeholder est interdit par le HTML5", "Le placeholder change la couleur de fond du champ", "Le placeholder empêche la validation HTML5"], 0),
            T("Une seule balise autofocus devrait idéalement être utilisée par page pour éviter de désorienter l'utilisateur.", True),
            T("autocomplete='off' garantit à 100% que tous les navigateurs n'afficheront jamais de suggestions sur ce champ.", False),
            M("Quelles affirmations sur placeholder sont correctes ?",
              ["Il fournit un exemple de format attendu", "Il n'est pas un substitut suffisant à un label accessible"],
              ["Il rend le champ obligatoire automatiquement", "Il remplace l'attribut value"]),
            M("Quels attributs influencent le comportement de saisie assistée d'un champ ?",
              ["autocomplete", "placeholder", "list"],
              ["colspan", "rowspan"]),
        ],
    ))

    quizzes.append(quiz(
        "Les liens de navigation et le SEO structurel",
        "Organiser la navigation interne pour les utilisateurs et les moteurs de recherche.",
        [
            S("Quel élément sémantique regroupe généralement le menu principal du site avec des liens <a> ?",
              ["<nav>", "<menu>", "<links>", "<sidebar>"]),
            S("Quel élément permet de signaler à un moteur de recherche l'URL canonique préférée d'une page dupliquée ?",
              ["<link rel='canonical'>", "<meta name='canonical'>", "<a rel='canonical'>", "<canonical>"]),
            S("Quelle structure de liens internes est généralement recommandée pour le SEO et l'accessibilité d'un site ?",
              ["Une hiérarchie de liens clairs et descriptifs reliant les pages importantes", "Aucun lien interne, uniquement des liens externes", "Des liens cachés en texte blanc sur fond blanc", "Des liens uniquement en JavaScript sans href"]),
            Sx("Quel élément HTML est recommandé pour fournir un lien de saut direct vers le contenu principal pour les utilisateurs au clavier ('skip link') ?",
               ["Un lien <a href='#main'> placé en tout début de page", "Un <nav> sans aucun lien", "Une <meta> dans le head", "Un <iframe> caché"], 0),
            T("Avoir plusieurs <nav> sur une même page est valide, par exemple un menu principal et un fil d'Ariane.", True),
            T("Les liens doivent toujours utiliser un texte d'ancre descriptif plutôt que 'cliquez ici', pour l'accessibilité et le SEO.", True),
            M("Quelles pratiques renforcent une navigation accessible et bien structurée ?",
              ["Utiliser des textes de lien descriptifs", "Marquer la navigation principale avec <nav>", "Permettre une navigation complète au clavier"],
              ["Cacher les liens de navigation avec display:none définitivement", "Utiliser uniquement des onclick sans attribut href"]),
            M("Quelles affirmations sur le balisage de navigation sont correctes ?",
              ["aria-label peut différencier plusieurs <nav> sur une même page", "Un fil d'Ariane (breadcrumb) peut être structuré avec une liste ordonnée"],
              ["Un site ne peut avoir qu'un seul élément de navigation au total", "<nav> doit obligatoirement contenir exactement trois liens"]),
        ],
    ))

    quizzes.append(quiz(
        "Le DOM et la relation entre HTML et JavaScript",
        "Comprendre comment le navigateur transforme le HTML en arbre manipulable.",
        [
            S("Que signifie l'acronyme DOM dans le contexte du développement web ?",
              ["Document Object Model", "Data Object Mapping", "Document Order Markup", "Dynamic Object Module"]),
            S("Sous quelle forme le navigateur représente-t-il un document HTML une fois analysé, pour permettre des manipulations via JavaScript ?",
              ["Un arbre de nœuds (le DOM)", "Une simple chaîne de texte brute", "Un tableau de pixels", "Une base de données SQL"]),
            S("Quelle méthode JavaScript courante permet de sélectionner un élément du DOM via son identifiant ?",
              ["document.getElementById()", "document.findById()", "document.selectId()", "document.queryId()"]),
            Sx("Que se passe-t-il typiquement quand JavaScript modifie un élément du DOM, par exemple son contenu texte ?",
               ["Le navigateur met à jour le rendu visuel de la page en conséquence", "Le fichier HTML source sur le serveur est modifié", "La page se recharge automatiquement", "Rien ne change visuellement"], 0),
            T("Le DOM peut différer du code source HTML original si du JavaScript a modifié la structure après le chargement initial.", True),
            T("Le HTML statique envoyé par le serveur est strictement identique en permanence au DOM affiché après exécution du JavaScript.", False),
            M("Quelles affirmations sur le DOM sont correctes ?",
              ["Il représente la structure du document sous forme d'arbre hiérarchique", "JavaScript peut y ajouter, modifier ou supprimer des nœuds dynamiquement"],
              ["Il est uniquement utilisé pour le style CSS, jamais pour JavaScript", "Il est généré uniquement côté serveur sans lien avec le navigateur"]),
            M("Quelles méthodes permettent de sélectionner des éléments dans le DOM en JavaScript ?",
              ["querySelector()", "getElementsByClassName()"],
              ["selectElementByCSS()", "fetchElement()"]),
        ],
    ))

    quizzes.append(quiz(
        "Métadonnées sociales : Open Graph et balises meta dédiées",
        "Contrôler l'aperçu d'une page partagée sur les réseaux sociaux.",
        [
            S("Quel préfixe de propriété meta est couramment utilisé pour contrôler l'aperçu d'une page partagée sur les réseaux sociaux (Open Graph) ?",
              ["og: (par exemple og:title)", "social:", "share:", "preview:"]),
            S("Quelle balise meta Open Graph définit l'image affichée dans l'aperçu de partage ?",
              ["og:image", "og:picture", "og:thumbnail", "og:photo"]),
            S("Quelle balise meta Open Graph définit le titre affiché dans l'aperçu de partage, potentiellement différent du <title> de la page ?",
              ["og:title", "og:heading", "og:name", "og:label"]),
            Sx("Pourquoi les balises Open Graph sont-elles complémentaires aux balises meta SEO classiques comme meta description ?",
               ["Elles ciblent spécifiquement l'affichage sur les réseaux sociaux plutôt que les résultats des moteurs de recherche", "Elles remplacent totalement le besoin de meta description", "Elles sont obligatoires pour que la page s'affiche dans un navigateur", "Elles définissent l'encodage de caractères"], 0),
            T("Les balises Open Graph se déclarent généralement comme des balises meta avec un attribut property plutôt que name.", True),
            T("Sans aucune balise Open Graph, un réseau social ne peut jamais générer un aperçu de partage.", False),
            M("Quelles balises meta sont couramment utilisées pour Open Graph ?",
              ["og:title", "og:description", "og:image"],
              ["seo:title", "twitter:author-only"]),
            M("Quelles affirmations sur les balises de partage social sont correctes ?",
              ["Elles influencent l'apparence d'un lien partagé sur certains réseaux", "Elles sont placées dans <head> comme les autres balises meta"],
              ["Elles modifient le contenu visible directement dans le corps de la page", "Elles sont obligatoires pour la validité HTML"]),
        ],
    ))

    quizzes.append(quiz(
        "Formulaires : groupes de boutons radio et cases à cocher",
        "Distinguer les choix exclusifs des choix multiples dans un formulaire.",
        [
            S("Quel type d'input permet de sélectionner une seule option parmi un groupe de choix exclusifs ?",
              ['type="radio"', 'type="checkbox"', 'type="select"', 'type="option"']),
            S("Quel type d'input permet de sélectionner indépendamment une ou plusieurs options, chacune pouvant être cochée ou non ?",
              ['type="checkbox"', 'type="radio"', 'type="multiple"', 'type="toggle"']),
            S("Quel attribut commun doit partager un ensemble de boutons radio pour qu'ils forment un seul groupe exclusif ?",
              ["name", "id", "value", "group"]),
            Sx("Quel attribut booléen permet de pré-cocher une case à cocher ou un bouton radio par défaut au chargement ?",
               ["checked", "selected", "default", "active"], 0),
            T("Deux boutons radio partageant le même attribut name forment un groupe où un seul peut être sélectionné à la fois.", True),
            T("Des cases à cocher partageant le même name s'excluent mutuellement comme des boutons radio.", False),
            M("Quelles affirmations sur les boutons radio et cases à cocher sont correctes ?",
              ["Chaque option doit idéalement avoir un <label> associé", "Le groupe radio repose sur un attribut name partagé"],
              ["Une case à cocher ne peut jamais être cochée par défaut", "Un bouton radio peut être combiné librement sans aucun attribut name"]),
            M("Quels éléments sont nécessaires pour un groupe de boutons radio accessible ?",
              ["Un <fieldset> englobant avec <legend>", "Des <label> associés à chaque input radio"],
              ["Un seul <label> global pour tout le groupe sans lien individuel", "Une balise <radio-group> dédiée qui n'existe pas en HTML"]),
        ],
    ))

    quizzes.append(quiz(
        "Les attributs lang et translate, internationalisation de base",
        "Adapter le contenu HTML à un public multilingue.",
        [
            S("Quel attribut permet d'indiquer qu'une portion de texte spécifique est dans une langue différente du reste du document ?",
              ["lang appliqué localement sur un élément", "translate uniquement", "dir", "locale"]),
            S("Quel attribut HTML peut indiquer à un outil de traduction automatique de ne pas traduire un contenu donné, comme un nom de marque ?",
              ["translate='no'", "lang='none'", "notranslate (attribut générique)", "skip-translate"]),
            S("Pourquoi est-il important de déclarer lang='fr' sur l'élément <html> d'une page rédigée en français ?",
              ["Pour une prononciation correcte par synthèse vocale et un meilleur référencement local", "Pour activer automatiquement un correcteur orthographique", "Pour changer l'encodage de caractères", "Pour empêcher la traduction automatique du navigateur"]),
            Sx("Que se passe-t-il généralement si l'attribut lang est absent ou incorrect sur une page multilingue ?",
               ["Les lecteurs d'écran ou outils de traduction peuvent mal interpréter ou mal prononcer le contenu", "La page ne s'affiche plus du tout", "Le CSS cesse de s'appliquer", "Les images ne se chargent plus"], 0),
            T("On peut combiner un attribut lang global sur <html> avec des attributs lang locaux sur des éléments spécifiques en langue différente.", True),
            T("L'attribut lang doit obligatoirement être écrit en majuscules, comme lang='FR'.", False),
            M("Quelles affirmations sur l'internationalisation HTML sont correctes ?",
              ["dir='rtl' adapte le sens de lecture pour les langues comme l'arabe", "lang aide les technologies d'assistance à choisir la voix ou les règles appropriées"],
              ["L'attribut lang change automatiquement la devise affichée", "Le HTML interdit nativement tout contenu multilingue dans une seule page"]),
            M("Quels éléments ou attributs participent à l'internationalisation d'une page ?",
              ["lang", "dir"],
              ["colspan", "controls"]),
        ],
    ))

    return quizzes
