from helpers_html import S, Sx, M, T, quiz

def get_quizzes():
    quizzes = []

    quizzes.append(quiz(
        "La structure de base d'un document HTML",
        "Le squelette minimal d'une page HTML : doctype, html, head, body.",
        [
            S("Quelle déclaration doit obligatoirement figurer en première ligne d'un document HTML5 ?",
              ["<!DOCTYPE html>", "<html5>", "<!HTML>", "<head>"]),
            S("Quel élément racine englobe l'intégralité du contenu visible et invisible d'une page HTML ?",
              ["<html>", "<body>", "<head>", "<doctype>"]),
            S("Quel élément contient les métadonnées d'une page (titre, liens vers les feuilles de style, etc.) ?",
              ["<head>", "<body>", "<meta>", "<header>"]),
            S("Quel élément contient le contenu visible affiché dans la fenêtre du navigateur ?",
              ["<body>", "<head>", "<main>", "<html>"]),
            T("Le doctype HTML5 est sensible à la casse et doit être écrit en minuscules.", False),
            T("Un document HTML5 valide ne peut contenir qu'un seul élément <body>.", True),
            M("Parmi les éléments suivants, lesquels sont des enfants directs obligatoires ou attendus de <html> ?",
              ["<head>", "<body>"],
              ["<title>", "<meta>", "<doctype>"]),
            M("Quelles affirmations sur le doctype HTML5 sont correctes ?",
              ["Il indique au navigateur d'utiliser le mode standard (non quirks)", "Il s'écrit <!DOCTYPE html>"],
              ["Il nécessite une URL de DTD complète comme en HTML4", "Il doit être placé dans <head>"]),
        ],
    ))

    quizzes.append(quiz(
        "Les balises sémantiques de structure (header, nav, main)",
        "Découvrir les éléments sémantiques HTML5 qui structurent une page.",
        [
            S("Quel élément sémantique représente l'en-tête d'une page ou d'une section ?",
              ["<header>", "<head>", "<top>", "<banner>"]),
            S("Quel élément sémantique est destiné à regrouper les liens de navigation principaux ?",
              ["<nav>", "<menu>", "<links>", "<navigation>"]),
            S("Quel élément sémantique représente le contenu principal et unique d'une page ?",
              ["<main>", "<content>", "<section>", "<body>"]),
            Sx("Combien d'éléments <main> visibles peut contenir une page HTML valide ?",
               ["Un seul", "Deux maximum", "Autant que de sections", "Aucune limite"], 0),
            T("L'élément <header> ne peut être utilisé qu'une seule fois par page, en tout début de document.", False),
            T("L'élément <main> ne doit pas être un descendant de <article>, <aside>, <header), <footer> ou <nav>.", True),
            M("Quels éléments font partie des balises sémantiques structurelles introduites par HTML5 ?",
              ["<header>", "<nav>", "<main>"],
              ["<div>", "<span>"]),
            M("Quels rôles ARIA implicites correspondent aux éléments sémantiques suivants ?",
              ["<nav> a le rôle implicite 'navigation'", "<main> a le rôle implicite 'main'"],
              ["<header> a le rôle implicite 'navigation'", "<nav> a le rôle implicite 'main'"]),
        ],
    ))

    quizzes.append(quiz(
        "Les balises sémantiques de contenu (article, section, aside, footer)",
        "Bien distinguer article, section, aside et footer dans un document HTML5.",
        [
            S("Quel élément représente un contenu autonome et réutilisable, comme un billet de blog ?",
              ["<article>", "<section>", "<div>", "<aside>"]),
            S("Quel élément regroupe thématiquement un ensemble de contenus, généralement avec un titre ?",
              ["<section>", "<article>", "<aside>", "<group>"]),
            S("Quel élément est utilisé pour du contenu connexe mais indirectement lié au contenu principal, comme une barre latérale ?",
              ["<aside>", "<section>", "<nav>", "<footer>"]),
            S("Quel élément représente le pied de page d'une section ou d'un document ?",
              ["<footer>", "<bottom>", "<end>", "<header>"]),
            T("Un <article> peut contenir plusieurs <section>, et une <section> peut contenir plusieurs <article>.", True),
            T("L'élément <aside> ne peut jamais être utilisé à l'intérieur d'un <article>.", False),
            M("Quels éléments peuvent légitimement apparaître plusieurs fois dans une même page HTML ?",
              ["<article>", "<section>", "<footer>"],
              ["<main>"]),
            M("Quelles affirmations sur <footer> sont correctes ?",
              ["Il peut contenir des informations d'auteur ou de copyright", "Il peut apparaître dans un <article>"],
              ["Il ne peut apparaître qu'une seule fois dans tout le document", "Il doit obligatoirement contenir un <nav>"]),
        ],
    ))

    quizzes.append(quiz(
        "Titres et paragraphes",
        "Hiérarchiser le contenu textuel avec les titres h1 à h6 et les paragraphes.",
        [
            S("Quel élément représente le titre de plus haut niveau (le plus important) d'une section ?",
              ["<h1>", "<h6>", "<title>", "<header>"]),
            S("Combien de niveaux de titres HTML existe-t-il, de h1 à h6 ?",
              ["6", "4", "5", "8"]),
            S("Quel élément délimite un paragraphe de texte ?",
              ["<p>", "<par>", "<text>", "<span>"]),
            Sx("Que se passe-t-il si l'on saute des niveaux de titres (par exemple passer de h1 à h4) ?",
               ["Le code reste valide mais nuit à l'accessibilité et à la structure logique", "Le navigateur refuse d'afficher la page", "Une erreur JavaScript est levée", "Le titre h4 est automatiquement converti en h2"], 0),
            T("L'élément <title> situé dans <head> définit le titre affiché dans l'onglet du navigateur, et non un titre visible dans la page.", True),
            T("Un document HTML peut contenir plusieurs éléments <h1>, notamment un par <section> ou <article>.", True),
            M("Quelles bonnes pratiques concernent la hiérarchie des titres ?",
              ["Respecter l'ordre logique des niveaux", "Utiliser un seul niveau de titre principal par section thématique"],
              ["Choisir le niveau de titre selon sa taille de police souhaitée", "Utiliser h1 uniquement pour le mettre en gras"]),
            M("Parmi ces éléments, lesquels servent à structurer du texte de paragraphe ou de titre ?",
              ["<p>", "<h2>"],
              ["<br>", "<hr>"]),
        ],
    ))

    quizzes.append(quiz(
        "Les listes : ul, ol et dl",
        "Comparer listes non ordonnées, ordonnées et listes de définitions.",
        [
            S("Quel élément crée une liste non ordonnée (à puces) ?",
              ["<ul>", "<ol>", "<li>", "<dl>"]),
            S("Quel élément crée une liste ordonnée (numérotée) ?",
              ["<ol>", "<ul>", "<list>", "<dl>"]),
            S("Quel élément représente un élément individuel à l'intérieur d'une liste ul ou ol ?",
              ["<li>", "<item>", "<dt>", "<dd>"]),
            S("Dans une liste de définitions <dl>, quel élément contient le terme à définir ?",
              ["<dt>", "<dd>", "<li>", "<term>"]),
            T("L'attribut 'start' permet de définir le numéro de départ d'une liste ordonnée <ol>.", True),
            T("Une liste <ul> peut être imbriquée à l'intérieur d'un élément <li> d'une autre liste.", True),
            M("Quels éléments composent une liste de définitions valide ?",
              ["<dl>", "<dt>", "<dd>"],
              ["<li>", "<ul>"]),
            M("Quels attributs sont valides sur l'élément <ol> ?",
              ["reversed", "start"],
              ["bullet", "numbered"]),
        ],
    ))

    quizzes.append(quiz(
        "Liens et ancres",
        "Créer des liens internes, externes et des ancres avec l'élément a.",
        [
            S("Quel élément permet de créer un hyperlien en HTML ?",
              ["<a>", "<link>", "<href>", "<nav>"]),
            S("Quel attribut de l'élément <a> définit la destination du lien ?",
              ["href", "src", "target", "to"]),
            S("Quelle valeur de l'attribut target ouvre le lien dans un nouvel onglet ou une nouvelle fenêtre ?",
              ["_blank", "_new", "_top", "_self"]),
            Sx("Comment créer un lien vers une ancre nommée 'section2' dans la même page ?",
               ['<a href="#section2">', '<a href="section2">', '<a anchor="section2">', '<a name="#section2">'], 0),
            T("Lorsqu'un lien externe s'ouvre dans un nouvel onglet avec target='_blank', il est recommandé d'ajouter rel='noopener' pour des raisons de sécurité.", True),
            T("L'attribut href est obligatoire pour que l'élément <a> soit reconnu comme un lien valide.", False),
            M("Quelles valeurs sont des valeurs valides pour l'attribut rel d'un lien <a> ?",
              ["noopener", "nofollow", "noreferrer"],
              ["blank", "external-only"]),
            M("Quelles affirmations sur les ancres internes sont correctes ?",
              ["On peut cibler un élément via son attribut id", "Le navigateur fait défiler la page jusqu'à l'élément ciblé"],
              ["Une ancre interne nécessite obligatoirement un élément <anchor>", "Les ancres internes ne fonctionnent qu'avec des balises <div>"]),
        ],
    ))

    quizzes.append(quiz(
        "Images et attributs (alt, srcset, picture)",
        "Insérer des images accessibles et adaptées à différentes résolutions.",
        [
            S("Quel élément permet d'insérer une image dans une page HTML ?",
              ["<img>", "<image>", "<src>", "<pic>"]),
            S("Quel attribut de <img> est essentiel pour l'accessibilité et fournit une description textuelle ?",
              ["alt", "title", "longdesc", "label"]),
            S("Quel attribut permet de fournir plusieurs sources d'image adaptées à différentes résolutions d'écran ?",
              ["srcset", "src-list", "sources", "multi-src"]),
            Sx("Quel élément parent permet de proposer plusieurs sources d'image alternatives selon le contexte (format, taille d'écran) avant un <img> de repli ?",
               ["<picture>", "<source>", "<figure>", "<media>"], 0),
            T("L'attribut alt doit être laissé vide (alt='') pour une image purement décorative sans valeur informative.", True),
            T("Sans attribut alt, un lecteur d'écran annoncera systématiquement le nom du fichier image.", False),
            M("Quels éléments ou attributs participent à des images responsives ?",
              ["srcset", "sizes", "<picture>"],
              ["zoom", "responsive-img"]),
            M("Quelles affirmations sur l'élément <img> sont correctes ?",
              ["Il s'agit d'un élément vide (sans contenu ni balise fermante)", "L'attribut src est obligatoire pour afficher une image"],
              ["Il doit toujours être placé dans un <figure>", "Il accepte un contenu texte entre balise ouvrante et fermante"]),
        ],
    ))

    quizzes.append(quiz(
        "Les tableaux HTML : structure de base",
        "Construire des tableaux avec table, tr, th et td.",
        [
            S("Quel élément crée un tableau HTML ?",
              ["<table>", "<grid>", "<tab>", "<tr>"]),
            S("Quel élément définit une ligne de tableau ?",
              ["<tr>", "<td>", "<th>", "<row>"]),
            S("Quel élément définit une cellule d'en-tête de tableau ?",
              ["<th>", "<td>", "<head>", "<tr>"]),
            S("Quel élément définit une cellule de données standard dans un tableau ?",
              ["<td>", "<th>", "<cell>", "<tr>"]),
            T("L'attribut scope sur <th> permet d'indiquer si l'en-tête s'applique à une colonne ou à une ligne, ce qui améliore l'accessibilité.", True),
            T("Un tableau HTML doit obligatoirement contenir un élément <thead>.", False),
            M("Quels éléments structurent les sections logiques d'un tableau ?",
              ["<thead>", "<tbody>", "<tfoot>"],
              ["<tgroup>", "<tsection>"]),
            M("Quelles affirmations sur <caption> sont correctes ?",
              ["Il fournit un titre ou une légende au tableau", "Il doit être le premier enfant de <table>"],
              ["Il remplace l'attribut alt des images", "Il est obligatoire pour qu'un tableau soit valide"]),
        ],
    ))

    quizzes.append(quiz(
        "Tableaux avancés : colspan et rowspan",
        "Fusionner des cellules de tableau horizontalement et verticalement.",
        [
            S("Quel attribut permet à une cellule de fusionner plusieurs colonnes ?",
              ["colspan", "rowspan", "colgroup", "merge"]),
            S("Quel attribut permet à une cellule de fusionner plusieurs lignes ?",
              ["rowspan", "colspan", "span", "rowgroup"]),
            Sx('Que produit le code <td colspan="2">Total</td> dans une ligne de tableau ?',
               ["La cellule occupe la largeur de deux colonnes", "La cellule occupe la hauteur de deux lignes", "Le tableau affiche deux cellules identiques", "Une erreur de validation HTML"], 0),
            S("Quel élément permet de regrouper et styliser un ensemble de colonnes d'un tableau ?",
              ["<colgroup>", "<col-group>", "<thead>", "<tbody>"]),
            T("La valeur par défaut de colspan et rowspan, si l'attribut est omis, est 1.", True),
            T("On peut combiner colspan et rowspan sur une même cellule <td>.", True),
            M("Quelles utilisations sont valides pour colspan/rowspan ?",
              ["Créer une cellule de titre qui chapeaute plusieurs colonnes", "Fusionner verticalement une cellule sur plusieurs lignes"],
              ["Fusionner deux tableaux distincts en un seul", "Définir le nombre total de colonnes du tableau"]),
            M("Quelles affirmations sur <col> et <colgroup> sont correctes ?",
              ["<col> permet d'appliquer un style à une colonne entière", "<colgroup> peut utiliser l'attribut span"],
              ["<col> contient le texte des cellules de données", "<colgroup> remplace obligatoirement <tbody>"]),
        ],
    ))

    quizzes.append(quiz(
        "Les formulaires : types d'input courants",
        "Découvrir les principaux types de champs de saisie HTML5.",
        [
            S("Quel élément définit un formulaire HTML ?",
              ["<form>", "<input>", "<fieldset>", "<field>"]),
            S("Quel type d'input HTML5 affiche un sélecteur de date natif ?",
              ['type="date"', 'type="text"', 'type="datetime"', 'type="calendar"']),
            S("Quel type d'input masque les caractères saisis, utile pour les mots de passe ?",
              ['type="password"', 'type="text"', 'type="hidden"', 'type="secret"']),
            Sx("Quel type d'input valide automatiquement le format d'une adresse email ?",
               ['type="email"', 'type="text"', 'type="mail"', 'type="address"'], 0),
            T("L'attribut method du formulaire peut valoir GET ou POST pour définir comment les données sont envoyées.", True),
            T('L\'input de type "number" empêche systématiquement la saisie de lettres, même via JavaScript.', False),
            M("Quels types d'input HTML5 existent réellement ?",
              ["range", "color", "tel"],
              ["currency", "fullname"]),
            M("Quelles affirmations sur l'élément <form> sont correctes ?",
              ["L'attribut action définit l'URL de soumission", "L'attribut method définit la méthode HTTP utilisée"],
              ["Un formulaire ne peut contenir qu'un seul champ input", "L'attribut action est obligatoire pour que le formulaire soit valide en HTML"]),
        ],
    ))

    quizzes.append(quiz(
        "Formulaires : label, fieldset et legend",
        "Associer correctement les étiquettes aux champs et regrouper les champs liés.",
        [
            S("Quel élément associe un texte descriptif à un champ de formulaire pour l'accessibilité ?",
              ["<label>", "<caption>", "<legend>", "<title>"]),
            S("Quel attribut de <label> permet de l'associer à un champ via son identifiant ?",
              ["for", "id", "name", "ref"]),
            S("Quel élément regroupe visuellement et sémantiquement un ensemble de champs liés dans un formulaire ?",
              ["<fieldset>", "<group>", "<section>", "<form-group>"]),
            S("Quel élément fournit un titre ou une légende à un <fieldset> ?",
              ["<legend>", "<caption>", "<label>", "<title>"]),
            T("On peut associer un label à un champ en plaçant directement l'input à l'intérieur de l'élément <label>, sans utiliser l'attribut for.", True),
            T("L'élément <legend> doit obligatoirement être le dernier enfant de <fieldset>.", False),
            M("Quelles méthodes permettent d'associer correctement un label à un champ ?",
              ["Utiliser l'attribut for avec l'id du champ", "Englober le champ directement dans la balise label"],
              ["Utiliser uniquement l'attribut placeholder du champ", "Ajouter un commentaire HTML décrivant le champ"]),
            M("Quelles affirmations sur <fieldset> sont correctes ?",
              ["L'attribut disabled désactive tous les champs qu'il contient", "Il peut contenir un élément <legend> en premier enfant"],
              ["Il ne peut contenir qu'un seul champ", "Il remplace obligatoirement l'élément <form>"]),
        ],
    ))

    quizzes.append(quiz(
        "Validation HTML5 des formulaires",
        "Utiliser required, pattern et autres attributs de validation natifs.",
        [
            S("Quel attribut rend un champ de formulaire obligatoire avant soumission ?",
              ["required", "mandatory", "must", "validate"]),
            S("Quel attribut permet de définir une expression régulière que la valeur du champ doit respecter ?",
              ["pattern", "regex", "format", "validate"]),
            S("Quel attribut limite le nombre maximal de caractères qu'un champ texte peut accepter ?",
              ["maxlength", "max", "limit", "size"]),
            Sx("Quels attributs permettent de définir une plage de valeurs numériques acceptables pour un input de type number ?",
               ["min et max", "minlength et maxlength", "low et high", "from et to"], 0),
            T("Un formulaire avec des champs invalides ne sera pas soumis par défaut si la validation HTML5 native est active.", True),
            T("L'attribut novalidate sur <form> désactive la validation HTML5 native lors de la soumission.", True),
            M("Quels attributs HTML5 participent à la validation native d'un formulaire ?",
              ["required", "pattern", "min"],
              ["validate-now", "check"]),
            M("Quelles affirmations sur la validation HTML5 sont correctes ?",
              ["Elle s'exécute côté client avant l'envoi des données", "Elle ne remplace pas une validation côté serveur pour la sécurité"],
              ["Elle garantit à elle seule la sécurité des données envoyées", "Elle est incompatible avec JavaScript"]),
        ],
    ))

    return quizzes
